.PHONY: all clean test

all:
	$(MAKE) -f Makefile.manual --directory=ascii
	$(MAKE) -f Makefile.manual --directory=loadtxt

test:
	$(MAKE) -f Makefile.manual --directory=ascii test
	$(MAKE) -f Makefile.manual --directory=loadtxt test

clean:
	$(MAKE) -f Makefile.manual --directory=ascii clean
	$(MAKE) -f Makefile.manual --directory=loadtxt clean
