SRCFYPP = \
          test_stdlib_math.fypp

PROGS_SRC = test_linspace.f90 test_logspace.f90 \
            test_math_arange.f90 \
            $(SRCFYPP:.fypp=.f90)

$(SRCFYPP): %.f90: %.fypp ../../common.fypp
	fypp -I../.. $(FYPPFLAGS) $< $@


include ../Makefile.manual.test.mk
