SRCFYPP = \
          test_linalg.fypp \
          test_linalg_matrix_property_checks.fypp

SRCGEN = $(SRCFYPP:.fypp=.f90)

PROGS_SRC = \
            $(SRCGEN)

$(SRCGEN): %.f90: %.fypp ../../common.fypp
	fypp -I../.. $(FYPPFLAGS) $< $@


include ../Makefile.manual.test.mk
