SRCFYPP = \
          test_simps.fypp \
          test_trapz.fypp
PROGS_SRC = \
            test_gauss.f90 \
            $(SRCFYPP:.fypp=.f90)

$(SRCFYPP): %.f90: %.fypp ../../common.fypp
	fypp -I../.. $(FYPPFLAGS) $< $@

include ../Makefile.manual.test.mk
