#:include "common.fypp"
#:set BETA_REAL_KINDS_TYPES = [item for item in REAL_KINDS_TYPES if item[0] in ('sp', 'dp', 'xdp')]
#:set BETA_CMPLX_KINDS_TYPES = [item for item in CMPLX_KINDS_TYPES if item[0] in ('sp', 'dp', 'xdp')]
#:set RC_KINDS_TYPES = BETA_REAL_KINDS_TYPES + BETA_CMPLX_KINDS_TYPES

program test_distribution_beta
    use stdlib_kinds, only : sp, dp, xdp
    use stdlib_error, only : check
    use stdlib_random, only : random_seed
    use stdlib_stats_distribution_beta, only : rbeta => rvs_beta,           &
                              beta_pdf => pdf_beta, beta_cdf => cdf_beta

    implicit none
    #:for k1, t1 in BETA_REAL_KINDS_TYPES
    ${t1}$, parameter :: ${k1}$tol = 1000 * epsilon(1.0_${k1}$)
    #:endfor
    logical ::  warn = .true.
    integer :: put, get

    put = 12345678
    call random_seed(put, get)

    call test_beta_random_generator

    #:for k1, t1 in RC_KINDS_TYPES
    call test_beta_rvs_${t1[0]}$${k1}$
    #:endfor

    #:for k1, t1 in RC_KINDS_TYPES
    call test_beta_pdf_${t1[0]}$${k1}$
    #:endfor

    #:for k1, t1 in RC_KINDS_TYPES
    call test_beta_cdf_${t1[0]}$${k1}$
    #:endfor

contains

    subroutine test_beta_random_generator
        integer, parameter :: num = 10000000, array_size = 1000
        integer :: i, j, freq(0:array_size-1)
        real(dp) :: chisq, expct

        print *, ""
        print *, "Test beta random generator with chi-squared"

        freq = 0
        do i = 1, num
            j = min(array_size - 1, int(array_size * beta_cdf(rbeta(2.0_dp, 5.0_dp, 0.0_dp), 2.0_dp, 5.0_dp, 0.0_dp)))
            freq(j) = freq(j) + 1
        end do

        chisq = 0.0_dp
        expct = num / array_size

        do i = 0, array_size - 1
           chisq = chisq + (freq(i) - expct) ** 2 / expct
        end do

        write(*,*) "The critical values for chi-squared with 1000 d. of f. is" &
            //" 1143.92"
        write(*,*) "Chi-squared for beta random generator is : ", chisq
        call check((chisq < 1143.9), &
            msg="beta randomness failed chi-squared test", warn=warn)

    end subroutine test_beta_random_generator

    #:for k1, t1 in RC_KINDS_TYPES
    subroutine test_beta_rvs_${t1[0]}$${k1}$
        integer, parameter :: k = 5, n = 10
        ${t1}$ :: res(n), ba, bb, loc
        integer :: i
        integer :: seed, get
    #:if t1[0] == "r"
      #! for real type
        ${t1}$ :: ans(n) = [0.23516498458385468E+00_${k1}$,                   &
                0.38906532525908948E+00_${k1}$,                               &
                0.34268730878829956E+00_${k1}$,                               &
                0.29513829946517944E+00_${k1}$,                               &
                0.19447886384116858E+00_${k1}$,                               &
                0.60383307933807373E+00_${k1}$,                               &
                0.58347225189208984E+00_${k1}$,                               &
                0.74638533592224121E+00_${k1}$,                               &
                0.55743497610092163E+00_${k1}$,                               &
                0.39149415493011475E+00_${k1}$]
    #:else
      #! for complex type
        ${t1}$ :: ans(n) =                                                     &
               [(0.44851309061050415E+00_${k1}$, 0.34970587491989136E+00_${k1}$), &
                (0.25030922889709473E+00_${k1}$, 0.55935305356979370E+00_${k1}$), &
                (0.69629210233688354E+00_${k1}$, 0.25098574161529541E+00_${k1}$), &
                (0.54261916875839233E+00_${k1}$, 0.45337703824043274E+00_${k1}$), &
                (0.25677326321601868E+00_${k1}$, 0.18765588104724884E+00_${k1}$), &
                (0.59211272001266479E+00_${k1}$, 0.72924208641052246E+00_${k1}$), &
                (0.75178939104080200E+00_${k1}$, 0.18360115587711334E+00_${k1}$), &
                (0.41408637166023254E+00_${k1}$, 0.36145636439323425E+00_${k1}$), &
                (0.47387075424194336E+00_${k1}$, 0.26313120126724243E+00_${k1}$), &
                (0.71398687362670898E+00_${k1}$, 0.51318806409835815E+00_${k1}$)]
    #:endif

        print *, "Test beta_distribution_rvs_${t1[0]}$${k1}$"
        seed = 639741825
        call random_seed(seed, get)

    #:if t1[0] == "r"
      #! for real type
        ba = 2.0_${k1}$; bb = 5.0_${k1}$; loc = 0._${k1}$
    #:else
      #! for complex type
        ba = (2.0_${k1}$, 0.7_${k1}$); bb = (5.0_${k1}$, 3.0_${k1}$); loc = (0._${k1}$, 0._${k1}$)
    #:endif

        do i = 1, k
            res(i) = rbeta(ba, bb, loc)
        end do

        res(k + 1 : n) = rbeta(ba, bb, k, loc)

        do i = 1, n
            call check(abs(res(i) - ans(i)) < ${k1}$tol,                      &
                       msg="beta_distribution_rvs_${t1[0]}$${k1}$ failed", &
                       warn=warn)
        end do
    end subroutine test_beta_rvs_${t1[0]}$${k1}$

    #:endfor

    #:for k1, t1 in RC_KINDS_TYPES
    subroutine test_beta_pdf_${t1[0]}$${k1}$
        ${t1}$ :: x1, x2(3,4), ba, bb, loc
        integer :: i
        integer :: seed, get
        real(${k1}$) :: res(15)
    #:if t1[0] == "r"
      #! for real type
        real(${k1}$), parameter :: ans(15) =                                   &
                 [1.23914337158203125E+00_${k1}$,            &
                  1.23914337158203125E+00_${k1}$,            &
                  1.23914337158203125E+00_${k1}$,            &
                  1.08365607261657715E+00_${k1}$,            &
                  1.04956150054931641E+00_${k1}$,            &
                  1.03561067581176758E+00_${k1}$,            &
                  1.22067928314208984E+00_${k1}$,            &
                  8.46962928771972656E-01_${k1}$,            &
                  2.52243280410766602E-01_${k1}$,            &
                  9.41652893066406250E-01_${k1}$,            &
                  6.57052993774414062E-01_${k1}$,            &
                  1.14095616340637207E+00_${k1}$,            &
                  9.09092426300048828E-01_${k1}$,            &
                  1.22890543937683105E+00_${k1}$,            &
                  4.40967559814453125E-01_${k1}$]
    #:else
      #! for complex type
        real(${k1}$), parameter :: ans(15) =                                   &
                 [1.15128993988037109E+00_${k1}$,            &
                  1.15128993988037109E+00_${k1}$,            &
                  1.15128993988037109E+00_${k1}$,            &
                  8.46223831176757812E-01_${k1}$,            &
                  3.30976486206054688E+00_${k1}$,            &
                  3.01892852783203125E+00_${k1}$,            &
                  1.23958110809326172E+00_${k1}$,            &
                  1.97296905517578125E+00_${k1}$,            &
                  1.17863655090332031E+00_${k1}$,            &
                  4.00447845458984375E-01_${k1}$,            &
                  2.92449951171875000E-02_${k1}$,            &
                  9.25743579864501953E-01_${k1}$,            &
                  2.15837764739990234E+00_${k1}$,            &
                  5.10101318359375000E-02_${k1}$,            &
                  1.03166580200195312E+00_${k1}$]
    #:endif

        print *, "Test beta_distribution_pdf_${t1[0]}$${k1}$"
        seed = 345987126
        call random_seed(seed, get)
    #:if t1[0] == "r"
      #! for real type
        ba = 2.0_${k1}$; bb = 5.0_${k1}$; loc = 0._${k1}$
    #:else
      #! for complex type
        ba = (2.0_${k1}$, 0.7_${k1}$); bb = (5.0_${k1}$, 3.0_${k1}$); loc = (0._${k1}$, 0._${k1}$)
    #:endif

        x1 = rbeta(ba, bb, loc)
        x2 = reshape(rbeta(ba, bb, 12, loc), [3,4])

        res(1:3) = beta_pdf(x1, ba, bb, loc)
        res(4:15) = reshape(beta_pdf(x2, ba, bb, loc), [12])

        do i = 1, 15
            call check(abs(res(i) - ans(i)) < ${k1}$tol,                      &
                       msg="beta_distribution_pdf_${t1[0]}$${k1}$ failed", &
                       warn=warn)
        end do
    end subroutine test_beta_pdf_${t1[0]}$${k1}$

    #:endfor

    #:for k1, t1 in RC_KINDS_TYPES
    subroutine test_beta_cdf_${t1[0]}$${k1}$
        ${t1}$ :: x1, x2(3,4), ba, bb, loc
        integer :: i
        integer :: seed, get
        real(${k1}$) :: res(15)
    #:if t1[0] == "r"
      #! for real type
        real(${k1}$), parameter :: ans(15) =                                   &
                 [0.37429335713386536E+00_${k1}$,            &
                  0.37429335713386536E+00_${k1}$,            &
                  0.37429335713386536E+00_${k1}$,            &
                  0.10568153858184814E+00_${k1}$,            &
                  0.61683785915374756E+00_${k1}$,            &
                  0.95208930969238281E-01_${k1}$,            &
                  0.34991249442100525E+00_${k1}$,            &
                  0.73912835121154785E+00_${k1}$,            &
                  0.95353639125823975E+00_${k1}$,            &
                  0.68856298923492432E+00_${k1}$,            &
                  0.36885082721710205E-01_${k1}$,            &
                  0.14866244792938232E+00_${k1}$,            &
                  0.74632394313812256E+00_${k1}$,            &
                  0.29785108566284180E+00_${k1}$,            &
                  0.14457702636718750E-01_${k1}$]
    #:else
      #! for complex type
        real(${k1}$), parameter :: ans(15) =                                   &
                 [0.14019477367401123E+00_${k1}$,            &
                  0.14019477367401123E+00_${k1}$,            &
                  0.14019477367401123E+00_${k1}$,            &
                  0.48782587051391602E+00_${k1}$,            &
                  0.19825363159179688E+00_${k1}$,            &
                  0.92399120330810547E-02_${k1}$,            &
                  0.55928134918212891E+00_${k1}$,            &
                  0.15336728096008301E+00_${k1}$,            &
                  0.31033802032470703E+00_${k1}$,            &
                  0.69235420227050781E+00_${k1}$,            &
                  0.92155790328979492E+00_${k1}$,            &
                  0.63153839111328125E+00_${k1}$,            &
                  0.86834430694580078E-01_${k1}$,            &
                  0.69353580474853516E+00_${k1}$,            &
                  0.59732055664062500E+00_${k1}$]
    #:endif

        print *, "Test beta_distribution_cdf_${t1[0]}$${k1}$"
        seed = 345987126
        call random_seed(seed, get)
    #:if t1[0] == "r"
      #! for real type
        ba = 2.0_${k1}$; bb = 5.0_${k1}$; loc = 0._${k1}$
    #:else
      #! for complex type
        ba = (2.0_${k1}$, 0.7_${k1}$); bb = (5.0_${k1}$, 3.0_${k1}$); loc = (0._${k1}$, 0._${k1}$)
    #:endif

        x1 = rbeta(ba, bb, loc)
        x2 = reshape(rbeta(ba, bb, 12, loc), [3,4])

        res(1:3) = beta_cdf(x1, ba, bb, loc)
        res(4:15) = reshape(beta_cdf(x2, ba, bb, loc), [12])

        do i = 1, 15
            call check(abs(res(i) - ans(i)) < ${k1}$tol,                      &
                       msg="beta_distribution_cdf_${t1[0]}$${k1}$ failed", &
                       warn=warn)
        end do
    end subroutine test_beta_cdf_${t1[0]}$${k1}$

    #:endfor

end program test_distribution_beta
