#:include "common.fypp"
#:set BETA_REAL_KINDS_TYPES = [item for item in REAL_KINDS_TYPES if item[0] in ('sp', 'dp', 'xdp')]
#:set BETA_CMPLX_KINDS_TYPES = [item for item in CMPLX_KINDS_TYPES if item[0] in ('sp', 'dp', 'xdp')]
#:set RC_KINDS_TYPES = BETA_REAL_KINDS_TYPES + BETA_CMPLX_KINDS_TYPES

program test_distribution_beta
    use stdlib_kinds, only : sp, dp, xdp
    use stdlib_error, only : check
    use stdlib_random, only : random_seed
    use stdlib_stats_distribution_beta, only : rbeta => rvs_beta,           &
                              beta_pdf => pdf_beta, beta_cdf => cdf_beta

    implicit none

    #:for k1, t1 in BETA_REAL_KINDS_TYPES
    ${t1}$, parameter :: ${k1}$tol = 1000 * epsilon(1.0_${k1}$)
    #:endfor

    logical :: warn = .true.
    integer :: put, get

    put = 12345678
    call random_seed(put, get)

    call test_beta_random_generator

    #:for k1, t1 in RC_KINDS_TYPES
    call test_beta_rvs_${t1[0]}$${k1}$
    #:endfor

    #:for k1, t1 in BETA_REAL_KINDS_TYPES
    call test_beta_pdf_${t1[0]}$${k1}$
    #:endfor

    #:for k1, t1 in BETA_REAL_KINDS_TYPES
    call test_beta_cdf_${t1[0]}$${k1}$
    #:endfor

contains

    subroutine test_beta_random_generator
        integer, parameter :: num = 10000000, array_size = 1000
        integer :: i, j, freq(0:array_size-1)
        real(dp) :: chisq, expct

        print *, ""
        print *, "Test beta random generator with chi-squared"

        freq = 0
        do i = 1, num
            j = min(array_size - 1, int(array_size * beta_cdf(rbeta(2.0_dp, 5.0_dp, 0.0_dp), 2.0_dp, 5.0_dp, 0.0_dp)))
            freq(j) = freq(j) + 1
        end do

        chisq = 0.0_dp
        expct = num / array_size

        do i = 0, array_size - 1
            chisq = chisq + (freq(i) - expct) ** 2 / expct
        end do

        write(*,*) "The critical values for chi-squared with 1000 d. of f. is" // " 1143.92"
        write(*,*) "Chi-squared for beta random generator is : ", chisq
        call check((chisq < 1143.9), msg="beta randomness failed chi-squared test", warn=warn)

    end subroutine test_beta_random_generator

    #:for k1, t1 in RC_KINDS_TYPES
    subroutine test_beta_rvs_${t1[0]}$${k1}$
        integer, parameter :: n = 100
        ${t1}$ :: res(n), ba, bb, loc
        integer :: i
        integer :: seed, get

        print *, "Test beta_distribution_rvs_${t1[0]}$${k1}$"
        seed = 639741825
        call random_seed(seed, get)

    #:if t1[0] == "r"
        ba = 2.0_${k1}$
        bb = 5.0_${k1}$
        loc = 0.0_${k1}$
    #:else
        ba = (2.0_${k1}$, 0.7_${k1}$)
        bb = (5.0_${k1}$, 3.0_${k1}$)
        loc = (0.0_${k1}$, 0.0_${k1}$)
    #:endif

        do i = 1, n
            res(i) = rbeta(ba, bb, loc)
        end do

    #:if t1[0] == "r"
        do i = 1, n
            call check((res(i) >= 0.0_${k1}$) .and. (res(i) <= 1.0_${k1}$), &
                       msg="beta_distribution_rvs_${t1[0]}$${k1}$ out of range", warn=warn)
        end do
    #:else
        do i = 1, n
            call check((real(res(i)) >= 0.0_${k1}$) .and. (real(res(i)) <= 1.0_${k1}$) .and. &
                       (aimag(res(i)) >= 0.0_${k1}$) .and. (aimag(res(i)) <= 1.0_${k1}$), &
                       msg="beta_distribution_rvs_${t1[0]}$${k1}$ out of range", warn=warn)
        end do
    #:endif

    end subroutine test_beta_rvs_${t1[0]}$${k1}$
    #:endfor

    #:for k1, t1 in BETA_REAL_KINDS_TYPES
    subroutine test_beta_pdf_${t1[0]}$${k1}$
        integer :: i
        real(${k1}$) :: res(15)
        real(${k1}$), parameter :: x_vals(15) = [                                &
            0.05000000000000000E+00_${k1}$,                                     &
            0.10000000000000001E+00_${k1}$,                                     &
            0.15000000000000002E+00_${k1}$,                                     &
            0.20000000000000001E+00_${k1}$,                                     &
            0.25000000000000000E+00_${k1}$,                                     &
            0.30000000000000004E+00_${k1}$,                                     &
            0.35000000000000003E+00_${k1}$,                                     &
            0.40000000000000002E+00_${k1}$,                                     &
            0.45000000000000001E+00_${k1}$,                                     &
            0.50000000000000000E+00_${k1}$,                                     &
            0.55000000000000004E+00_${k1}$,                                     &
            0.59999999999999998E+00_${k1}$,                                     &
            0.70000000000000007E+00_${k1}$,                                     &
            0.80000000000000004E+00_${k1}$,                                     &
            0.90000000000000002E+00_${k1}$]
        real(${k1}$), parameter :: ans(15) = [                                   &
            1.22175937500000087E+00_${k1}$,                                     &
            1.96829999999999972E+00_${k1}$,                                     &
            2.34902812499999891E+00_${k1}$,                                     &
            2.45759999999999978E+00_${k1}$,                                     &
            2.37304687500000044E+00_${k1}$,                                     &
            2.16089999999999938E+00_${k1}$,                                     &
            1.87431562500000037E+00_${k1}$,                                     &
            1.55520000000000058E+00_${k1}$,                                     &
            1.23533437500000032E+00_${k1}$,                                     &
            9.37499999999999889E-01_${k1}$,                                     &
            6.76603124999999861E-01_${k1}$,                                     &
            4.60800000000000043E-01_${k1}$,                                     &
            1.70099999999999946E-01_${k1}$,                                     &
            3.83999999999999897E-02_${k1}$,                                     &
            2.69999999999999928E-03_${k1}$]

        print *, "Test beta_distribution_pdf_${t1[0]}$${k1}$"

        do i = 1, 15
            res(i) = beta_pdf(x_vals(i), 2.0_${k1}$, 5.0_${k1}$, 0.0_${k1}$)
        end do

        do i = 1, 15
            call check(abs(res(i) - ans(i)) < max(${k1}$tol, 1.0e-12_${k1}$), &
                       msg="beta_distribution_pdf_${t1[0]}$${k1}$ failed", warn=warn)
        end do

    end subroutine test_beta_pdf_${t1[0]}$${k1}$
    #:endfor

    #:for k1, t1 in BETA_REAL_KINDS_TYPES
    subroutine test_beta_cdf_${t1[0]}$${k1}$
        integer :: i
        real(${k1}$) :: res(15)
        real(${k1}$), parameter :: x_vals(15) = [                                &
            0.05000000000000000E+00_${k1}$,                                     &
            0.10000000000000001E+00_${k1}$,                                     &
            0.15000000000000002E+00_${k1}$,                                     &
            0.20000000000000001E+00_${k1}$,                                     &
            0.25000000000000000E+00_${k1}$,                                     &
            0.30000000000000004E+00_${k1}$,                                     &
            0.35000000000000003E+00_${k1}$,                                     &
            0.40000000000000002E+00_${k1}$,                                     &
            0.45000000000000001E+00_${k1}$,                                     &
            0.50000000000000000E+00_${k1}$,                                     &
            0.55000000000000004E+00_${k1}$,                                     &
            0.59999999999999998E+00_${k1}$,                                     &
            0.70000000000000007E+00_${k1}$,                                     &
            0.80000000000000004E+00_${k1}$,                                     &
            0.90000000000000002E+00_${k1}$]
        real(${k1}$), parameter :: ans(15) = [                                   &
            3.27738281249999944E-02_${k1}$,                                     &
            1.14265000000000019E-01_${k1}$,                                     &
            2.23515703125000020E-01_${k1}$,                                     &
            3.44640000000000224E-01_${k1}$,                                     &
            4.66064453125000000E-01_${k1}$,                                     &
            5.79825000000000257E-01_${k1}$,                                     &
            6.80920078124999995E-01_${k1}$,                                     &
            7.66720000000000068E-01_${k1}$,                                     &
            8.36432578124999937E-01_${k1}$,                                     &
            8.90625000000000000E-01_${k1}$,                                     &
            9.30801953125000026E-01_${k1}$,                                     &
            9.59040000000000004E-01_${k1}$,                                     &
            9.89064999999999972E-01_${k1}$,                                     &
            9.98399999999999954E-01_${k1}$,                                     &
            9.99944999999999973E-01_${k1}$]

        print *, "Test beta_distribution_cdf_${t1[0]}$${k1}$"

        do i = 1, 15
            res(i) = beta_cdf(x_vals(i), 2.0_${k1}$, 5.0_${k1}$, 0.0_${k1}$)
        end do

        do i = 1, 15
            call check(abs(res(i) - ans(i)) < max(${k1}$tol, 1.0e-12_${k1}$), &
                       msg="beta_distribution_cdf_${t1[0]}$${k1}$ failed", warn=warn)
        end do

    end subroutine test_beta_cdf_${t1[0]}$${k1}$
    #:endfor

end program test_distribution_beta
