#:include "common.fypp"
#:set BETA_REAL_KINDS_TYPES = [item for item in REAL_KINDS_TYPES if item[0] in ('sp', 'dp', 'xdp')]
#:set BETA_CMPLX_KINDS_TYPES = [item for item in CMPLX_KINDS_TYPES if item[0] in ('sp', 'dp', 'xdp')]
#:set RC_KINDS_TYPES = BETA_REAL_KINDS_TYPES + BETA_CMPLX_KINDS_TYPES

program test_distribution_beta
    use stdlib_kinds, only : sp, dp, xdp
    use stdlib_error, only : check
    use stdlib_random, only : random_seed
    use stdlib_stats_distribution_beta, only : rbeta => rvs_beta,           &
                              beta_pdf => pdf_beta, beta_cdf => cdf_beta

    implicit none
    #:for k1, t1 in BETA_REAL_KINDS_TYPES
    ${t1}$, parameter :: ${k1}$tol = 1000 * epsilon(1.0_${k1}$)
    #:endfor
    logical :: warn = .true.
    integer :: put, get

    put = 12345678
    call random_seed(put, get)

    call test_beta_random_generator

    #:for k1, t1 in RC_KINDS_TYPES
    call test_beta_rvs_${t1[0]}$${k1}$
    #:endfor

    #:for k1, t1 in RC_KINDS_TYPES
    call test_beta_pdf_${t1[0]}$${k1}$
    #:endfor

    #:for k1, t1 in RC_KINDS_TYPES
    call test_beta_cdf_${t1[0]}$${k1}$
    #:endfor

contains

    subroutine test_beta_random_generator
        integer, parameter :: num = 10000000, array_size = 1000
        integer :: i, j, freq(0:array_size-1)
        real(dp) :: chisq, expct

        print *, ""
        print *, "Test beta random generator with chi-squared"

        freq = 0
        do i = 1, num
            j = min(array_size - 1, int(array_size * beta_cdf(rbeta(2.0_dp, 5.0_dp, 0.0_dp), 2.0_dp, 5.0_dp, 0.0_dp)))
            freq(j) = freq(j) + 1
        end do

        chisq = 0.0_dp
        expct = num / array_size

        do i = 0, array_size - 1
           chisq = chisq + (freq(i) - expct) ** 2 / expct
        end do

        write(*,*) "The critical values for chi-squared with 1000 d. of f. is" &
            //" 1143.92"
        write(*,*) "Chi-squared for beta random generator is : ", chisq
        call check((chisq < 1143.9), &
            msg="beta randomness failed chi-squared test", warn=warn)

    end subroutine test_beta_random_generator

    #:for k1, t1 in RC_KINDS_TYPES
    subroutine test_beta_rvs_${t1[0]}$${k1}$
        integer, parameter :: k = 5, n = 10
        ${t1}$ :: res(n), ans(n), ba, bb, loc
        integer :: i
        integer :: seed, get

        print *, "Test beta_distribution_rvs_${t1[0]}$${k1}$"
        seed = 639741825
        call random_seed(seed, get)

    #:if t1[0] == "r"
        ba = 2.0_${k1}$; bb = 5.0_${k1}$; loc = 0._${k1}$
    #:else
        ba = (2.0_${k1}$, 0.7_${k1}$); bb = (5.0_${k1}$, 3.0_${k1}$); loc = (0._${k1}$, 0._${k1}$)
    #:endif

        do i = 1, k
            res(i) = rbeta(ba, bb, loc)
        end do
        res(k + 1 : n) = rbeta(ba, bb, k, loc)

        seed = 639741825
        call random_seed(seed, get)
        do i = 1, n
            ans(i) = rbeta(ba, bb, loc)
        end do

        do i = 1, n
            call check(abs(res(i) - ans(i)) < ${k1}$tol,                      &
                       msg="beta_distribution_rvs_${t1[0]}$${k1}$ failed", &
                       warn=warn)
        end do
    end subroutine test_beta_rvs_${t1[0]}$${k1}$

    #:endfor

    #:for k1, t1 in RC_KINDS_TYPES
    subroutine test_beta_pdf_${t1[0]}$${k1}$
        ${t1}$ :: x1, x2(3,4), ba, bb, loc
        integer :: i
        real(${k1}$) :: res(15)
    #:if t1[0] == "r"
      #! for real type
        real(${k1}$), parameter :: ans(15) =                                   &
                 [2.45759999999999978E+00_${k1}$,            &
                  2.45759999999999978E+00_${k1}$,            &
                  2.45759999999999978E+00_${k1}$,            &
                  1.22175937500000087E+00_${k1}$,            &
                  1.96829999999999972E+00_${k1}$,            &
                  2.34902812499999891E+00_${k1}$,            &
                  2.37304687500000044E+00_${k1}$,            &
                  2.16089999999999938E+00_${k1}$,            &
                  1.87431562500000037E+00_${k1}$,            &
                  1.55520000000000058E+00_${k1}$,            &
                  1.23533437500000032E+00_${k1}$,            &
                  9.37499999999999889E-01_${k1}$,            &
                  4.60800000000000043E-01_${k1}$,            &
                  1.70099999999999946E-01_${k1}$,            &
                  3.83999999999999897E-02_${k1}$]
    #:else
      #! for complex type
        real(${k1}$), parameter :: ans(15) =                                   &
                 [2.77620563793055197E+00_${k1}$,            &
                  2.77620563793055197E+00_${k1}$,            &
                  2.77620563793055197E+00_${k1}$,            &
                  4.35133599581893460E+00_${k1}$,            &
                  5.11042526155962751E+00_${k1}$,            &
                  3.91417214341107966E+00_${k1}$,            &
                  3.25033085838892477E+00_${k1}$,            &
                  2.44104116333175813E+00_${k1}$,            &
                  1.74312991236416215E+00_${k1}$,            &
                  1.18399939600181159E+00_${k1}$,            &
                  7.62828448855675023E-01_${k1}$,            &
                  4.63554726571548781E-01_${k1}$,            &
                  1.79353320295729979E-01_${k1}$,            &
                  5.09635475047793968E-02_${k1}$,            &
                  6.17909755246391895E-03_${k1}$]
    #:endif

        print *, "Test beta_distribution_pdf_${t1[0]}$${k1}$"
    #:if t1[0] == "r"
        ba = 2.0_${k1}$; bb = 5.0_${k1}$; loc = 0._${k1}$
        x1 = 0.2_${k1}$
        x2 = reshape([0.05_${k1}$, 0.1_${k1}$, 0.15_${k1}$, 0.25_${k1}$,      &
                      0.3_${k1}$, 0.35_${k1}$, 0.4_${k1}$, 0.45_${k1}$,       &
                      0.5_${k1}$, 0.6_${k1}$, 0.7_${k1}$, 0.8_${k1}$], [3,4])
    #:else
        ba = (2.0_${k1}$, 0.7_${k1}$); bb = (5.0_${k1}$, 3.0_${k1}$); loc = (0._${k1}$, 0._${k1}$)
        x1 = (0.2_${k1}$, 0.3_${k1}$)
        x2 = reshape([(0.05_${k1}$, 0.05_${k1}$), (0.1_${k1}$, 0.1_${k1}$),   &
                      (0.15_${k1}$, 0.2_${k1}$), (0.25_${k1}$, 0.25_${k1}$),   &
                      (0.3_${k1}$, 0.3_${k1}$), (0.35_${k1}$, 0.35_${k1}$),    &
                      (0.4_${k1}$, 0.4_${k1}$), (0.45_${k1}$, 0.45_${k1}$),    &
                      (0.5_${k1}$, 0.5_${k1}$), (0.6_${k1}$, 0.55_${k1}$),     &
                      (0.7_${k1}$, 0.6_${k1}$), (0.8_${k1}$, 0.7_${k1}$)], [3,4])
    #:endif

        res(1:3) = beta_pdf(x1, ba, bb, loc)
        res(4:15) = reshape(beta_pdf(x2, ba, bb, loc), [12])

        do i = 1, 15
            call check(abs(res(i) - ans(i)) < ${k1}$tol,                      &
                       msg="beta_distribution_pdf_${t1[0]}$${k1}$ failed", &
                       warn=warn)
        end do
    end subroutine test_beta_pdf_${t1[0]}$${k1}$

    #:endfor

    #:for k1, t1 in RC_KINDS_TYPES
    subroutine test_beta_cdf_${t1[0]}$${k1}$
        ${t1}$ :: x1, x2(3,4), ba, bb, loc
        integer :: i
        real(${k1}$) :: res(15)
    #:if t1[0] == "r"
      #! for real type
        real(${k1}$), parameter :: ans(15) =                                   &
                 [3.44640000000000224E-01_${k1}$,            &
                  3.44640000000000224E-01_${k1}$,            &
                  3.44640000000000224E-01_${k1}$,            &
                  3.27738281249999944E-02_${k1}$,            &
                  1.14265000000000019E-01_${k1}$,            &
                  2.23515703125000020E-01_${k1}$,            &
                  4.66064453125000000E-01_${k1}$,            &
                  5.79825000000000257E-01_${k1}$,            &
                  6.80920078124999995E-01_${k1}$,            &
                  7.66720000000000068E-01_${k1}$,            &
                  8.36432578124999937E-01_${k1}$,            &
                  8.90625000000000000E-01_${k1}$,            &
                  9.59040000000000004E-01_${k1}$,            &
                  9.89064999999999972E-01_${k1}$,            &
                  9.98399999999999954E-01_${k1}$]
    #:else
      #! for complex type
        real(${k1}$), parameter :: ans(15) =                                   &
                 [2.64331290012673414E-01_${k1}$,            &
                  2.64331290012673414E-01_${k1}$,            &
                  2.64331290012673414E-01_${k1}$,            &
                  8.86382195944738702E-03_${k1}$,            &
                  4.81500626030448228E-02_${k1}$,            &
                  1.40607931860570912E-01_${k1}$,            &
                  3.28430860699885308E-01_${k1}$,            &
                  4.44713005546652551E-01_${k1}$,            &
                  5.57213246702040532E-01_${k1}$,            &
                  6.59756977764087704E-01_${k1}$,            &
                  7.48497876310954546E-01_${k1}$,            &
                  8.21680689855777691E-01_${k1}$,            &
                  9.05920357339824456E-01_${k1}$,            &
                  9.51254168091690833E-01_${k1}$,            &
                  9.82801096697218157E-01_${k1}$]
    #:endif

        print *, "Test beta_distribution_cdf_${t1[0]}$${k1}$"
    #:if t1[0] == "r"
        ba = 2.0_${k1}$; bb = 5.0_${k1}$; loc = 0._${k1}$
        x1 = 0.2_${k1}$
        x2 = reshape([0.05_${k1}$, 0.1_${k1}$, 0.15_${k1}$, 0.25_${k1}$,      &
                      0.3_${k1}$, 0.35_${k1}$, 0.4_${k1}$, 0.45_${k1}$,       &
                      0.5_${k1}$, 0.6_${k1}$, 0.7_${k1}$, 0.8_${k1}$], [3,4])
    #:else
        ba = (2.0_${k1}$, 0.7_${k1}$); bb = (5.0_${k1}$, 3.0_${k1}$); loc = (0._${k1}$, 0._${k1}$)
        x1 = (0.2_${k1}$, 0.3_${k1}$)
        x2 = reshape([(0.05_${k1}$, 0.05_${k1}$), (0.1_${k1}$, 0.1_${k1}$),   &
                      (0.15_${k1}$, 0.2_${k1}$), (0.25_${k1}$, 0.25_${k1}$),   &
                      (0.3_${k1}$, 0.3_${k1}$), (0.35_${k1}$, 0.35_${k1}$),    &
                      (0.4_${k1}$, 0.4_${k1}$), (0.45_${k1}$, 0.45_${k1}$),    &
                      (0.5_${k1}$, 0.5_${k1}$), (0.6_${k1}$, 0.55_${k1}$),     &
                      (0.7_${k1}$, 0.6_${k1}$), (0.8_${k1}$, 0.7_${k1}$)], [3,4])
    #:endif

        res(1:3) = beta_cdf(x1, ba, bb, loc)
        res(4:15) = reshape(beta_cdf(x2, ba, bb, loc), [12])

        do i = 1, 15
            call check(abs(res(i) - ans(i)) < ${k1}$tol,                      &
                       msg="beta_distribution_cdf_${t1[0]}$${k1}$ failed", &
                       warn=warn)
        end do
    end subroutine test_beta_cdf_${t1[0]}$${k1}$

    #:endfor

end program test_distribution_beta
