#:include "common.fypp"
#:set GAMMA_REAL_KINDS_TYPES = [item for item in REAL_KINDS_TYPES if item[0] in ('sp', 'dp', 'xdp')]
#:set GAMMA_CMPLX_KINDS_TYPES = [item for item in CMPLX_KINDS_TYPES if item[0] in ('sp', 'dp', 'xdp')]
#:set RC_KINDS_TYPES = GAMMA_REAL_KINDS_TYPES + GAMMA_CMPLX_KINDS_TYPES
program test_distribution_gamma
    use stdlib_kinds, only : sp, dp, xdp
    use stdlib_error, only : check
    use stdlib_random, only : random_seed
    use stdlib_stats_distribution_gamma, only : rgamma => rvs_gamma,           &
                              gamma_pdf => pdf_gamma, gamma_cdf => cdf_gamma

    implicit none
    #:for k1, t1 in GAMMA_REAL_KINDS_TYPES
    ${t1}$, parameter :: ${k1}$tol = 1000 * epsilon(1.0_${k1}$)
    #:endfor
    logical ::  warn = .true.
    integer :: put, get

    put = 12345678
    call random_seed(put, get)

    call test_gamma_random_generator

    #:for k1, t1 in RC_KINDS_TYPES
    call test_gamma_rvs_${t1[0]}$${k1}$
    #:endfor

    #:for k1, t1 in RC_KINDS_TYPES
    call test_gamma_pdf_${t1[0]}$${k1}$
    #:endfor

    #:for k1, t1 in RC_KINDS_TYPES
    call test_gamma_cdf_${t1[0]}$${k1}$
    #:endfor

contains

    subroutine test_gamma_random_generator
        integer, parameter :: num = 10000000, array_size = 1000
        integer :: i, j, freq(0:array_size-1)
        real(dp) :: chisq, expct

        print *, ""
        print *, "Test gamma random generator with chi-squared"

        freq = 0
        do i = 1, num
            j = min(array_size - 1, int(array_size * gamma_cdf(rgamma(2.0_dp, 1.5_dp, 0.0_dp), 2.0_dp, 1.5_dp, 0.0_dp)))
            freq(j) = freq(j) + 1
        end do

        chisq = 0.0_dp
        expct = num / array_size

        do i = 0, array_size - 1
           chisq = chisq + (freq(i) - expct) ** 2 / expct
        end do

        write(*,*) "The critical values for chi-squared with 1000 d. of f. is" &
            //" 1143.92"
        write(*,*) "Chi-squared for gamma random generator is : ", chisq
        call check((chisq < 1143.9), &
            msg="gamma randomness failed chi-squared test", warn=warn)

    end subroutine test_gamma_random_generator

    #:for k1, t1 in RC_KINDS_TYPES
    subroutine test_gamma_rvs_${t1[0]}$${k1}$
        integer, parameter :: k = 5, n = 10
        ${t1}$ :: res(n), gshape, rate, loc
        integer :: i
        integer :: seed, get
    #:if t1[0] == "r"
      #! for real type
        ${t1}$ :: ans(n) = [0.85758907497718881E+00_${k1}$,                   &
                0.10206623865526088E+01_${k1}$,                   &
                0.99753931024198652E+00_${k1}$,                   &
                0.97653359790345837E+00_${k1}$,                   &
                0.41853482638322031E+00_${k1}$,                   &
                0.22012288073086305E+01_${k1}$,                   &
                0.20639542613306583E+01_${k1}$,                   &
                0.31794669730880196E+01_${k1}$,                   &
                0.19329744662223283E+01_${k1}$,                   &
                0.10257959670932112E+01_${k1}$]
    #:else
      #! for complex type
          ${t1}$ :: ans(n) =                                                     &
               [(0.10719863437214860E+01_${k1}$, 0.46775532101393817E+00_${k1}$), &
                (0.42382516926807199E+00_${k1}$, 0.96340496644915242E+00_${k1}$), &
                (0.27515360091357881E+01_${k1}$, 0.14837198853150384E+00_${k1}$), &
                (0.14536367104245527E+01_${k1}$, 0.56852736336951546E+00_${k1}$), &
                (0.34559143458416108E+00_${k1}$, 0.49621768536248831E-01_${k1}$), &
                (0.19657884897696515E+01_${k1}$, 0.31124314799641007E+01_${k1}$), &
                (0.34155160623540454E+01_${k1}$, 0.50494893389401867E-01_${k1}$), &
                (0.94594398345216283E+00_${k1}$, 0.45691588305890623E+00_${k1}$), &
                (0.11493158751025962E+01_${k1}$, 0.12944763723941669E+00_${k1}$), &
                (0.29691469633592286E+01_${k1}$, 0.11617408197125868E+01_${k1}$)]
    #:endif

        print *, "Test gamma_distribution_rvs_${t1[0]}$${k1}$"
        seed = 639741825
        call random_seed(seed, get)

    #:if t1[0] == "r"
      #! for real type
        gshape = 2.0_${k1}$; rate = 1.0_${k1}$; loc = 0._${k1}$
    #:else
      #! for complex type
        gshape = (2.0_${k1}$, 0.7_${k1}$); rate = (0.8_${k1}$, 1.2_${k1}$); loc = (0._${k1}$, 0._${k1}$)
    #:endif

        do i = 1, k
            res(i) = rgamma(gshape, rate, loc)
        end do

        res(k + 1 : n) = rgamma(gshape, rate, k, loc)

        do i = 1, n
            call check(abs(res(i) - ans(i)) < ${k1}$tol,                      &
                       msg="gamma_distribution_rvs_${t1[0]}$${k1}$ failed", &
                       warn=warn)
        end do
    end subroutine test_gamma_rvs_${t1[0]}$${k1}$

    #:endfor

    #:for k1, t1 in RC_KINDS_TYPES
    subroutine test_gamma_pdf_${t1[0]}$${k1}$
        ${t1}$ :: x1, x2(3,4), gshape, rate, loc
        integer :: i
        integer :: seed, get
        real(${k1}$) :: res(15)
    #:if t1[0] == "r"
      #! for real type
        real(${k1}$), parameter :: ans(15) =                                   &
                 [0.34495412572168702E-01_${k1}$,            &
                  0.34495412572168702E-01_${k1}$,            &
                  0.34495412572168702E-01_${k1}$,            &
                  0.29116634347089576E+00_${k1}$,            &
                  0.28338290850731419E+00_${k1}$,            &
                  0.27922270935613580E+00_${k1}$,            &
                  0.36440665523348268E+00_${k1}$,            &
                  0.24379209619143690E+00_${k1}$,            &
                  0.63815638087140761E-01_${k1}$,            &
                  0.25844600948718583E+00_${k1}$,            &
                  0.17268118913523492E+00_${k1}$,            &
                  0.31181223194308201E+00_${k1}$,            &
                  0.24027095040543100E+00_${k1}$,            &
                  0.36765502365831573E+00_${k1}$,            &
                  0.99011714088769636E-01_${k1}$]
    #:else
      #! for complex type
        real(${k1}$), parameter :: ans(15) =                                   &
                 [0.11554282574059280E+00_${k1}$,            &
                  0.11554282574059280E+00_${k1}$,            &
                  0.11554282574059280E+00_${k1}$,            &
                  0.92682318951901516E-01_${k1}$,            &
                  0.40166849087286064E+00_${k1}$,            &
                  0.37468980496232690E+00_${k1}$,            &
                  0.14712363446345353E+00_${k1}$,            &
                  0.22561628567985192E+00_${k1}$,            &
                  0.12765403024301183E+00_${k1}$,            &
                  0.39182498867847366E-01_${k1}$,            &
                  0.25873533461032836E-02_${k1}$,            &
                  0.10105832622792976E+00_${k1}$,            &
                  0.24044091896609491E+00_${k1}$,            &
                  0.49885356046115958E-02_${k1}$,            &
                  0.11085827028639165E+00_${k1}$]
    #:endif

        print *, "Test gamma_distribution_pdf_${t1[0]}$${k1}$"
        seed = 345987126
        call random_seed(seed, get)
    #:if t1[0] == "r"
      #! for real type
        gshape = 2.0_${k1}$; rate = 1.0_${k1}$; loc = 0._${k1}$
    #:else
      #! for complex type
        gshape = (2.0_${k1}$, 0.7_${k1}$); rate = (0.8_${k1}$, 1.2_${k1}$); loc = (0._${k1}$, 0._${k1}$)
    #:endif

        x1 = rgamma(gshape, rate, loc)
        x2 = reshape(rgamma(gshape, rate, 12, loc), [3,4])

        res(1:3) = gamma_pdf(x1, gshape, rate, loc)
        res(4:15) = reshape(gamma_pdf(x2, gshape, rate, loc), [12])

        do i = 1, 15
            call check(abs(res(i) - ans(i)) < ${k1}$tol,                      &
                       msg="gamma_distribution_pdf_${t1[0]}$${k1}$ failed", &
                       warn=warn)
        end do
    end subroutine test_gamma_pdf_${t1[0]}$${k1}$

    #:endfor

    #:for k1, t1 in RC_KINDS_TYPES
    subroutine test_gamma_cdf_${t1[0]}$${k1}$
        ${t1}$ :: x1, x2(3,4), gshape, rate, loc
        integer :: i
        integer :: seed, get
        real(${k1}$) :: res(15)
    #:if t1[0] == "r"
      #! for real type
        real(${k1}$), parameter :: ans(15) =                                   &
                 [0.95856447024923161E+00_${k1}$,            &
                  0.95856447024923161E+00_${k1}$,            &
                  0.95856447024923161E+00_${k1}$,            &
                  0.78989843937516711E-01_${k1}$,            &
                  0.56793164492527640E+00_${k1}$,            &
                  0.69398686246667538E-01_${k1}$,            &
                  0.31709086664429768E+00_${k1}$,            &
                  0.64538378729933876E+00_${k1}$,            &
                  0.92092738488690244E+00_${k1}$,            &
                  0.61792198504673790E+00_${k1}$,            &
                  0.19854195697723341E-01_${k1}$,            &
                  0.99267229424260651E-01_${k1}$,            &
                  0.65180771852756031E+00_${k1}$,            &
                  0.25154115213140924E+00_${k1}$,            &
                  0.56823696777839551E-02_${k1}$]
    #:else
      #! for complex type
        real(${k1}$), parameter :: ans(15) =                                   &
                 [0.30546556548076713E-01_${k1}$,            &
                  0.30546556548076713E-01_${k1}$,            &
                  0.30546556548076713E-01_${k1}$,            &
                  0.28163392764814024E+00_${k1}$,            &
                  0.93663475343392596E-01_${k1}$,            &
                  0.34623100575641867E-02_${k1}$,            &
                  0.33855418983076070E+00_${k1}$,            &
                  0.65637763837417527E-01_${k1}$,            &
                  0.15878146335804994E+00_${k1}$,            &
                  0.48425923323146416E+00_${k1}$,            &
                  0.85584614493283579E+00_${k1}$,            &
                  0.41677260318284231E+00_${k1}$,            &
                  0.33377215439459634E-01_${k1}$,            &
                  0.48072346126598581E+00_${k1}$,            &
                  0.38686165822935510E+00_${k1}$]
    #:endif

        print *, "Test gamma_distribution_cdf_${t1[0]}$${k1}$"
        seed = 345987126
        call random_seed(seed, get)
    #:if t1[0] == "r"
      #! for real type
        gshape = 2.0_${k1}$; rate = 1.0_${k1}$; loc = 0._${k1}$
    #:else
      #! for complex type
        gshape = (2.0_${k1}$, 0.7_${k1}$); rate = (0.8_${k1}$, 1.2_${k1}$); loc = (0._${k1}$, 0._${k1}$)
    #:endif

        x1 = rgamma(gshape, rate, loc)
        x2 = reshape(rgamma(gshape, rate, 12, loc), [3,4])

        res(1:3) = gamma_cdf(x1, gshape, rate, loc)
        res(4:15) = reshape(gamma_cdf(x2, gshape, rate, loc), [12])

        do i = 1, 15
            call check(abs(res(i) - ans(i)) < ${k1}$tol,                      &
                       msg="gamma_distribution_cdf_${t1[0]}$${k1}$ failed", &
                       warn=warn)
        end do
    end subroutine test_gamma_cdf_${t1[0]}$${k1}$

    #:endfor

end program test_distribution_gamma
