#:include "common.fypp"
#:set RANKS = range(1, 2+1)
#:set R_KINDS_TYPES = list(zip(REAL_KINDS, REAL_TYPES, REAL_SUFFIX))
#:set C_KINDS_TYPES = list(zip(CMPLX_KINDS, CMPLX_TYPES, CMPLX_SUFFIX))
#:set KINDS_TYPES = R_KINDS_TYPES+C_KINDS_TYPES
#! define ranks without parentheses
#:def rksfx2(rank)
#{if rank > 0}#${":," + ":," * (rank - 1)}$#{endif}#
#:enddef
submodule (stdlib_sparse_spmv) stdlib_sparse_spmv_bsr
    use stdlib_optval, only: optval
    use stdlib_linalg_blas, only: gemv, gemm
contains

    !! spmv_bsr OOP wrappers
    #:for k1, t1, s1 in (KINDS_TYPES)
    #:for rank in RANKS
    !> OOP rank=${rank}$ wrapper: unpacks BSR matrix and delegates to kernel
    module subroutine spmv_bsr_${rank}$d_${s1}$(matrix, vec_x, vec_y, alpha, beta, op)
        type(BSR_${s1}$_type), intent(in) :: matrix
        ${t1}$, intent(in)    :: vec_x${ranksuffix(rank)}$
        ${t1}$, intent(inout) :: vec_y${ranksuffix(rank)}$
        ${t1}$, intent(in), optional :: alpha
        ${t1}$, intent(in), optional :: beta
        character(1), intent(in), optional :: op

        ${t1}$ :: alpha_, beta_
        character(1) :: op_

        alpha_ = optval(x=alpha, default=one_${s1}$ )
        beta_  = optval(x=beta , default=zero_${s1}$)
        op_    = optval(x=op   , default=sparse_op_none)

        call spmv_kernel_bsr_${rank}$d_${s1}$(matrix%data, matrix%rowptr, matrix%col, &
            matrix%storage, vec_x, vec_y, alpha_, beta_, op_)
    end subroutine spmv_bsr_${rank}$d_${s1}$
    #:endfor
    #:endfor

    !! spmv_bsr non-OOP kernels
    #:for k1, t1, s1 in (KINDS_TYPES)

    !> Non-OOP rank=1 kernel for BSR SpMV
    subroutine spmv_kernel_bsr_1d_${s1}$(data, rowptr, col, storage, vec_x, vec_y, alpha, beta, op)
        ${t1}$, intent(in), contiguous :: data(:,:,:)
        integer(ilp), intent(in), contiguous :: rowptr(:), col(:)
        integer(ilp), intent(in) :: storage
        ${t1}$, intent(in), contiguous    :: vec_x(:)
        ${t1}$, intent(inout), contiguous :: vec_y(:)
        ${t1}$, intent(in) :: alpha
        ${t1}$, intent(in) :: beta
        character(1), intent(in) :: op
        integer(ilp) :: nrows, ncols
        integer(ilp) :: nbrow, bi, bj, p, br, bc
        integer(ilp) :: row_i_start, col_j_start, i_max_i, j_max_j
        integer(ilp) :: row_j_start, col_i_start, i_max_j, j_max_i
        #:if t1.startswith('complex')
        ${t1}$, allocatable :: xwork_bc(:)
        ${t1}$, allocatable :: ywork_br(:)
        #:endif

        if(beta == zero_${s1}$) then
            vec_y = zero_${s1}$
        else
            vec_y = beta * vec_y
        endif

        br = size(data, dim=1)
        bc = size(data, dim=2)
        nbrow = size(rowptr) - 1
        if(op == sparse_op_none) then
            nrows = size(vec_y)
            ncols = size(vec_x)
        else
            nrows = size(vec_x)
            ncols = size(vec_y)
        end if

        if( storage == sparse_full .and. op == sparse_op_none ) then
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    call gemv('N', m=i_max_i, n=j_max_j, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        x=vec_x(col_j_start:), incx=1, beta=one_${s1}$, &
                        y=vec_y(row_i_start:), incy=1)
                end do
            end do

        else if( storage == sparse_full .and. op == sparse_op_transpose ) then
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    call gemv('T', m=i_max_i, n=j_max_j, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        x=vec_x(row_i_start:), incx=1, beta=one_${s1}$, &
                        y=vec_y(col_j_start:), incy=1)
                end do
            end do

        else if( storage == sparse_lower .and. op /= sparse_op_hermitian ) then
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    call gemv('N', m=i_max_i, n=j_max_j, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        x=vec_x(col_j_start:), incx=1, beta=one_${s1}$, &
                        y=vec_y(row_i_start:), incy=1)

                    if (bi == bj) cycle

                    row_j_start = (bj - 1) * br + 1
                    if (row_j_start > nrows) cycle
                    i_max_j = min(br, nrows - row_j_start + 1)
                    col_i_start = (bi - 1) * bc + 1
                    if (col_i_start > ncols) cycle
                    j_max_i = min(bc, ncols - col_i_start + 1)
                    call gemv('T', m=i_max_i, n=j_max_j, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        x=vec_x(col_i_start:), incx=1, beta=one_${s1}$, &
                        y=vec_y(row_j_start:), incy=1)
                end do
            end do

        else if( storage == sparse_upper .and. op /= sparse_op_hermitian ) then
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    call gemv('N', m=i_max_i, n=j_max_j, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        x=vec_x(col_j_start:), incx=1, beta=one_${s1}$, &
                        y=vec_y(row_i_start:), incy=1)

                    if (bi == bj) cycle

                    row_j_start = (bj - 1) * br + 1
                    if (row_j_start > nrows) cycle
                    i_max_j = min(br, nrows - row_j_start + 1)
                    col_i_start = (bi - 1) * bc + 1
                    if (col_i_start > ncols) cycle
                    j_max_i = min(bc, ncols - col_i_start + 1)
                    call gemv('T', m=i_max_i, n=j_max_j, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        x=vec_x(col_i_start:), incx=1, beta=one_${s1}$, &
                        y=vec_y(row_j_start:), incy=1)
                end do
            end do

        #:if t1.startswith('complex')
        else if( storage == sparse_full .and. op == sparse_op_hermitian ) then
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    call gemv('C', m=i_max_i, n=j_max_j, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        x=vec_x(row_i_start:), incx=1, beta=one_${s1}$, &
                        y=vec_y(col_j_start:), incy=1)
                end do
            end do

        else if( storage == sparse_lower .and. op == sparse_op_hermitian ) then
            if(.not.allocated(xwork_bc)) allocate(xwork_bc(bc))
            if(.not.allocated(ywork_br)) allocate(ywork_br(br))
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    xwork_bc(1:j_max_j) = conjg(vec_x(col_j_start:col_j_start+j_max_j-1))
                    ywork_br(1:i_max_i) = zero_${s1}$
                    call gemv('N', m=i_max_i, n=j_max_j, alpha=one_${s1}$, a=data(1:,1:,p), lda=br, &
                        x=xwork_bc, incx=1, beta=zero_${s1}$, y=ywork_br, incy=1)
                    vec_y(row_i_start:row_i_start+i_max_i-1) = vec_y(row_i_start:row_i_start+i_max_i-1) + &
                        alpha * conjg(ywork_br(1:i_max_i))

                    if (bi == bj) cycle

                    row_j_start = (bj - 1) * br + 1
                    if (row_j_start > nrows) cycle
                    i_max_j = min(br, nrows - row_j_start + 1)
                    col_i_start = (bi - 1) * bc + 1
                    if (col_i_start > ncols) cycle
                    j_max_i = min(bc, ncols - col_i_start + 1)
                    call gemv('C', m=i_max_i, n=j_max_j, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        x=vec_x(col_i_start:), incx=1, beta=one_${s1}$, &
                        y=vec_y(row_j_start:), incy=1)
                end do
            end do

        else if( storage == sparse_upper .and. op == sparse_op_hermitian ) then
            if(.not.allocated(xwork_bc)) allocate(xwork_bc(bc))
            if(.not.allocated(ywork_br)) allocate(ywork_br(br))
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    xwork_bc(1:j_max_j) = conjg(vec_x(col_j_start:col_j_start+j_max_j-1))
                    ywork_br(1:i_max_i) = zero_${s1}$
                    call gemv('N', m=i_max_i, n=j_max_j, alpha=one_${s1}$, a=data(1:,1:,p), lda=br, &
                        x=xwork_bc, incx=1, beta=zero_${s1}$, y=ywork_br, incy=1)
                    vec_y(row_i_start:row_i_start+i_max_i-1) = vec_y(row_i_start:row_i_start+i_max_i-1) + &
                        alpha * conjg(ywork_br(1:i_max_i))

                    if (bi == bj) cycle

                    row_j_start = (bj - 1) * br + 1
                    if (row_j_start > nrows) cycle
                    i_max_j = min(br, nrows - row_j_start + 1)
                    col_i_start = (bi - 1) * bc + 1
                    if (col_i_start > ncols) cycle
                    j_max_i = min(bc, ncols - col_i_start + 1)
                    call gemv('C', m=i_max_i, n=j_max_j, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        x=vec_x(col_i_start:), incx=1, beta=one_${s1}$, &
                        y=vec_y(row_j_start:), incy=1)
                end do
            end do
        #:endif
        end if
    end subroutine spmv_kernel_bsr_1d_${s1}$

    !> Non-OOP rank=2 kernel for BSR SpMV
    subroutine spmv_kernel_bsr_2d_${s1}$(data, rowptr, col, storage, vec_x, vec_y, alpha, beta, op)
        ${t1}$, intent(in), contiguous :: data(:,:,:)
        integer(ilp), intent(in), contiguous :: rowptr(:), col(:)
        integer(ilp), intent(in) :: storage
        ${t1}$, intent(in), contiguous    :: vec_x(:,:)
        ${t1}$, intent(inout), contiguous :: vec_y(:,:)
        ${t1}$, intent(in) :: alpha
        ${t1}$, intent(in) :: beta
        character(1), intent(in) :: op
        integer(ilp) :: nrows, ncols
        integer(ilp) :: nbrow, bi, bj, p, br, bc, nrhs
        integer(ilp) :: row_i_start, col_j_start, i_max_i, j_max_j
        integer(ilp) :: row_j_start, col_i_start, i_max_j, j_max_i
        #:if t1.startswith('complex')
        ${t1}$, allocatable :: xwork_bc(:,:)
        ${t1}$, allocatable :: ywork_br(:,:)
        #:endif

        if(beta == zero_${s1}$) then
            vec_y = zero_${s1}$
        else
            vec_y = beta * vec_y
        endif

        br = size(data, dim=1)
        bc = size(data, dim=2)
        nbrow = size(rowptr) - 1
        nrhs = size(vec_x, dim=2)
        if(op == sparse_op_none) then
            nrows = size(vec_y, dim=1)
            ncols = size(vec_x, dim=1)
        else
            nrows = size(vec_x, dim=1)
            ncols = size(vec_y, dim=1)
        end if

        if( storage == sparse_full .and. op == sparse_op_none ) then
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    call gemm('N','N', m=i_max_i, n=nrhs, k=j_max_j, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        b=vec_x(col_j_start:, :), ldb=j_max_j, beta=one_${s1}$, &
                        c=vec_y(row_i_start:, :), ldc=i_max_i)
                end do
            end do

        else if( storage == sparse_full .and. op == sparse_op_transpose ) then
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    call gemm('T','N', m=j_max_j, n=nrhs, k=i_max_i, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        b=vec_x(row_i_start:, :), ldb=i_max_i, beta=one_${s1}$, &
                        c=vec_y(col_j_start:, :), ldc=j_max_j)
                end do
            end do

        else if( storage == sparse_lower .and. op /= sparse_op_hermitian ) then
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    call gemm('N','N', m=i_max_i, n=nrhs, k=j_max_j, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        b=vec_x(col_j_start:, :), ldb=j_max_j, beta=one_${s1}$, &
                        c=vec_y(row_i_start:, :), ldc=i_max_i)

                    if (bi == bj) cycle

                    row_j_start = (bj - 1) * br + 1
                    if (row_j_start > nrows) cycle
                    i_max_j = min(br, nrows - row_j_start + 1)
                    col_i_start = (bi - 1) * bc + 1
                    if (col_i_start > ncols) cycle
                    j_max_i = min(bc, ncols - col_i_start + 1)
                    call gemm('T','N', m=j_max_j, n=nrhs, k=i_max_i, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        b=vec_x(col_i_start:, :), ldb=j_max_i, beta=one_${s1}$, &
                        c=vec_y(row_j_start:, :), ldc=i_max_j)
                end do
            end do

        else if( storage == sparse_upper .and. op /= sparse_op_hermitian ) then
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    call gemm('N','N', m=i_max_i, n=nrhs, k=j_max_j, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        b=vec_x(col_j_start:, :), ldb=j_max_j, beta=one_${s1}$, &
                        c=vec_y(row_i_start:, :), ldc=i_max_i)

                    if (bi == bj) cycle

                    row_j_start = (bj - 1) * br + 1
                    if (row_j_start > nrows) cycle
                    i_max_j = min(br, nrows - row_j_start + 1)
                    col_i_start = (bi - 1) * bc + 1
                    if (col_i_start > ncols) cycle
                    j_max_i = min(bc, ncols - col_i_start + 1)
                    call gemm('T','N', m=j_max_j, n=nrhs, k=i_max_i, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        b=vec_x(col_i_start:, :), ldb=j_max_i, beta=one_${s1}$, &
                        c=vec_y(row_j_start:, :), ldc=i_max_j)
                end do
            end do

        #:if t1.startswith('complex')
        else if( storage == sparse_full .and. op == sparse_op_hermitian ) then
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    call gemm('C','N', m=j_max_j, n=nrhs, k=i_max_i, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        b=vec_x(row_i_start:, :), ldb=i_max_i, beta=one_${s1}$, &
                        c=vec_y(col_j_start:, :), ldc=j_max_j)
                end do
            end do

        else if( storage == sparse_lower .and. op == sparse_op_hermitian ) then
            if(.not.allocated(xwork_bc)) allocate(xwork_bc(bc,nrhs))
            if(.not.allocated(ywork_br)) allocate(ywork_br(br,nrhs))
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    xwork_bc(1:j_max_j, :) = conjg(vec_x(col_j_start:col_j_start+j_max_j-1, :))
                    ywork_br(1:i_max_i, :) = zero_${s1}$
                    call gemm('N','N', m=i_max_i, n=nrhs, k=j_max_j, alpha=one_${s1}$, a=data(1:,1:,p), lda=br, &
                        b=xwork_bc, ldb=bc, beta=zero_${s1}$, c=ywork_br, ldc=br)
                    vec_y(row_i_start:row_i_start+i_max_i-1, :) = vec_y(row_i_start:row_i_start+i_max_i-1, :) + &
                        alpha * conjg(ywork_br(1:i_max_i, :))

                    if (bi == bj) cycle

                    row_j_start = (bj - 1) * br + 1
                    if (row_j_start > nrows) cycle
                    i_max_j = min(br, nrows - row_j_start + 1)
                    col_i_start = (bi - 1) * bc + 1
                    if (col_i_start > ncols) cycle
                    j_max_i = min(bc, ncols - col_i_start + 1)
                    call gemm('C','N', m=j_max_j, n=nrhs, k=i_max_i, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        b=vec_x(col_i_start:, :), ldb=j_max_i, beta=one_${s1}$, &
                        c=vec_y(row_j_start:, :), ldc=i_max_j)
                end do
            end do

        else if( storage == sparse_upper .and. op == sparse_op_hermitian ) then
            if(.not.allocated(xwork_bc)) allocate(xwork_bc(bc,nrhs))
            if(.not.allocated(ywork_br)) allocate(ywork_br(br,nrhs))
            do bi = 1, nbrow
                row_i_start = (bi - 1) * br + 1
                if (row_i_start > nrows) cycle
                i_max_i = min(br, nrows - row_i_start + 1)
                do p = rowptr(bi), rowptr(bi+1)-1
                    bj = col(p)
                    col_j_start = (bj - 1) * bc + 1
                    if (col_j_start > ncols) cycle
                    j_max_j = min(bc, ncols - col_j_start + 1)
                    xwork_bc(1:j_max_j, :) = conjg(vec_x(col_j_start:col_j_start+j_max_j-1, :))
                    ywork_br(1:i_max_i, :) = zero_${s1}$
                    call gemm('N','N', m=i_max_i, n=nrhs, k=j_max_j, alpha=one_${s1}$, a=data(1:,1:,p), lda=br, &
                        b=xwork_bc, ldb=bc, beta=zero_${s1}$, c=ywork_br, ldc=br)
                    vec_y(row_i_start:row_i_start+i_max_i-1, :) = vec_y(row_i_start:row_i_start+i_max_i-1, :) + &
                        alpha * conjg(ywork_br(1:i_max_i, :))

                    if (bi == bj) cycle

                    row_j_start = (bj - 1) * br + 1
                    if (row_j_start > nrows) cycle
                    i_max_j = min(br, nrows - row_j_start + 1)
                    col_i_start = (bi - 1) * bc + 1
                    if (col_i_start > ncols) cycle
                    j_max_i = min(bc, ncols - col_i_start + 1)
                    call gemm('C','N', m=j_max_j, n=nrhs, k=i_max_i, alpha=alpha, a=data(1:,1:,p), lda=br, &
                        b=vec_x(col_i_start:, :), ldb=j_max_i, beta=one_${s1}$, &
                        c=vec_y(row_j_start:, :), ldc=i_max_j)
                end do
            end do
        #:endif
        end if
    end subroutine spmv_kernel_bsr_2d_${s1}$

    #:endfor

end submodule stdlib_sparse_spmv_bsr
