CPPFLAGS = -I../..
OBJS = ../../stdlib_experimental_ascii.o \
       ../../stdlib_experimental_error.o

.PHONY: all clean
.SUFFIXES: .f90 .o

all: test_ascii

test_ascii: test_ascii.f90 $(OBJS)
	$(FC) $(FCFLAGS) $(CPPFLAGS) $< -o $@ $(OBJS)

%.o: %.mod

clean:
	$(RM) test_ascii
	$(RM) *.o *.mod
