PROG = test_ascii
OBJS = test_ascii.o

CPPFLAGS = -I../..
LDFLAGS = -L../.. -lstdlib

.PHONY: all clean test

all: $(PROG)

$(PROG): $(OBJS)
	$(FC) $(FFLAGS) $(CPPFLAGS) -o $@ $(OBJS) $(LDFLAGS)

test:
	./$(PROG)

clean:
	$(RM) $(PROG) $(OBJS) *.mod

%.o: %.f90
	$(FC) $(FFLAGS) $(CPPFLAGS) -c $<
