PROGS_SRC = test_loadtxt.f90 \
			test_savetxt.f90 \
			test_loadtxt_qp.f90 \
			test_savetxt_qp.f90

CLEAN_FILES = tmp.dat tmp_qp.dat

CPPFLAGS = -I../..
LDFLAGS = -L../.. -lstdlib



OBJS = $(PROGS_SRC:.f90=.o)
PROGS = $(OBJS:.o=)
TESTPROGS = $(PROGS:=TEST)

.PHONY: all clean test $(TESTPROGS)

all: $(PROGS)

test: $(TESTPROGS)

$(TESTPROGS):
	./$(@:TEST=)

clean:
	$(RM) $(PROGS) $(OBJS) $(CLEAN_FILES)

%.o: %.f90
	$(FC) $(FFLAGS) $(CPPFLAGS) -c $<

$(PROGS): %: %.o
	$(FC) $(FFLAGS) $(CPPFLAGS) -o $@ $^ $(LDFLAGS)
