PROGS_SRC = test_loadtxt.f90 \
			test_savetxt.f90 \
			test_loadtxt_qp.f90 \
			test_savetxt_qp.f90

CPPFLAGS = -I../..
LDFLAGS = -L../.. -lstdlib


OBJS = $(PROGS_SRC:.f90=.o)
PROGS = $(OBJS:.o=)



.PHONY: all clean test

all: $(PROGS)

$(PROGS): %: %.o
	$(FC) $(FFLAGS) $(CPPFLAGS) -o $@ $^ $(LDFLAGS)

test:
	./test_loadtxt
	./test_loadtxt_qp
	./test_savetxt
	./test_savetxt_qp

clean:
	$(RM) $(PROGS) $(OBJS) tmp.dat tmp_qp.dat

%.o: %.f90
	$(FC) $(FFLAGS) $(CPPFLAGS) -c $<
