CC ?= gcc
CXX ?= g++

CPPFLAGS += -I. -I../.. -I..
LDFLAGS += -L../.. -L.. -lstdlib-testing -lstdlib

PROGS =  test_hash_functions
TESTPROGS = $(PROGS:=TEST)

all: $(PROGS)

test: $(TESTPROGS)

$(TESTPROGS):
	./$(@:TEST=)

test_hash_functions: test_hash_functions.f90 generate_hash_arrays.o libc_hash.a
	$(FC) $(FFLAGS) $(CPPFLAGS) -L. -o $@ $^ $(LDFLAGS) -lc_hash -lstdc++

generate_hash_arrays.o: generate_hash_arrays.cpp libc_hash.a
	$(CXX) $(CXXFLAGS) -c generate_hash_arrays.cpp -o generate_hash_arrays.o

libc_hash.a: SpookyV2.o SpookyV2Test.o pengyhash.o nmhash_scalar.o waterhash.o
	ar rcs libc_hash.a SpookyV2.o SpookyV2Test.o pengyhash.o \
               nmhash_scalar.o waterhash.o

pengyhash.o: pengyhash.c pengyhash.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c pengyhash.c -o pengyhash.o

waterhash.o: waterhash.c waterhash.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c waterhash.c -o waterhash.o

SpookyV2.o: SpookyV2.cpp SpookyV2.h
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c SpookyV2.cpp -o SpookyV2.o

SpookyV2Test.o: SpookyV2Test.cpp SpookyV2.h
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c SpookyV2Test.cpp -o SpookyV2Test.o

nmhash_scalar.o: nmhash_scalar.c nmhash_scalar.h
	$(CC) $(CFLAGS) $(CPPFLAGS) -c nmhash_scalar.c -o nmhash_scalar.o

clean:
	rm nmhash_scalar.o SpookyV2Test.o SpookyV2.o waterhash.o pengyhash.o \
           libc_hash.a generate_hash_arrays.o $(PROGS) *.*mod\
	   *.bin


