!Default: compile the ansi module
#if !defined STDLIB_ANSI
#define STDLIB_ANSI 1
#endif

!Default: compile the bitsets module
#if !defined STDLIB_BITSETS
#define STDLIB_BITSETS 1
#endif

!Default: compile the hashmaps module
#if !defined STDLIB_HASHMAPS
#define STDLIB_HASHMAPS 1
#endif

!Default: compile the io module
#if !defined STDLIB_IO
#define STDLIB_IO 1
#endif

!Default: compile the linalg_iterative module
#if !defined STDLIB_LINALG_ITERATIVE
#define STDLIB_LINALG_ITERATIVE 1
#endif

!Default: compile the logger module
#if !defined STDLIB_LOGGER
#define STDLIB_LOGGER 1
#endif

!Default: compile the quadrature module
#if !defined STDLIB_QUADRATURE
#define STDLIB_QUADRATURE 1
#endif

!Default: compile the specialmatrices module
#if !defined STDLIB_SPECIALMATRICES
#define STDLIB_SPECIALMATRICES 1
#endif

!Default: compile the stringlist module
#if !defined STDLIB_STRINGLIST
#define STDLIB_STRINGLIST 1
#endif

!Default: compile the system module
#if !defined STDLIB_SYSTEM
#define STDLIB_SYSTEM 1
#endif

!Default: compile the stats module
#if !defined STDLIB_STATS
#define STDLIB_STATS 1
#endif
