!Default: compile the ansi module
#if !defined STDLIB_ANSI
#define STDLIB_ANSI 1
#endif

!Default: compile the bitsets module
#if !defined STDLIB_BITSETS
#define STDLIB_BITSETS 1
#endif

!Default: compile the hashmaps module
#if !defined STDLIB_HASHMAPS
#define STDLIB_HASHMAPS 1
#endif

!Default: compile the io module
#if !defined STDLIB_IO
#define STDLIB_IO 1
#endif

!Default: compile the logger module
#if !defined STDLIB_LOGGER
#define STDLIB_LOGGER 1
#endif

!Default: compile the stats module
#if !defined STDLIB_STATS
#define STDLIB_STATS 1
#endif
