LIB = libstdlib.a

OBJS = stdlib_experimental_ascii.o \
       stdlib_experimental_error.o \
       stdlib_experimental_io.o \
	   f18estop.o

MODS = $(OBJS:.o=.mod)

.PHONY: all clean

all: $(LIB)

$(LIB): $(OBJS)
	ar rcs $@ $(OBJS)

clean:
	$(RM) $(LIB) $(OBJS) $(MODS)

%.o: %.f90
	$(FC) $(FFLAGS) -c $<
