SRC = stdlib_experimental_ascii.f90 \
      stdlib_experimental_error.f90 \
      stdlib_experimental_io.f90 \
      f18estop.f90

LIB = libstdlib.a



OBJS = $(SRC:.f90=.o)
MODS = $(OBJS:.o=.mod)
SMODS = $(OBJS:.o=*.smod)

.PHONY: all clean

all: $(LIB)

$(LIB): $(OBJS)
	ar rcs $@ $(OBJS)

clean:
	$(RM) $(LIB) $(OBJS) $(MODS) $(SMODS)

%.o: %.f90
	$(FC) $(FFLAGS) -c $<


# Fortran module dependencies
f18estop.o: stdlib_experimental_error.o
