module stdlib_codata
    !! Codata Constants - Autogenerated
    use stdlib_kinds, only: dp, int32
    use stdlib_codata_type
    private

integer(int32), parameter, public :: YEAR = 2018 !! Year of release.

type(codata_constant), parameter, public :: ALPHA_PARTICLE_ELECTRON_MASS_RATIO = &
codata_constant("alpha particle-electron mass ratio", &
7294.29954142_dp, 0.00000024_dp, &
"") !! alpha particle-electron mass ratio

type(codata_constant), parameter, public :: ALPHA_PARTICLE_MASS = &
codata_constant("alpha particle mass", &
6.6446573357e-27_dp, 0.0000000020e-27_dp, &
"kg") !! alpha particle mass

type(codata_constant), parameter, public :: ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT = &
codata_constant("alpha particle mass energy equivalent", &
5.9719201914e-10_dp, 0.0000000018e-10_dp, &
"J") !! alpha particle mass energy equivalent

type(codata_constant), parameter, public :: ALPHA_PARTICLE_MASS_ENERGY_EQUIVALENT_IN_MEV = &
codata_constant("alpha particle mass energy equivalent in MeV", &
3727.3794066_dp, 0.0000011_dp, &
"MeV") !! alpha particle mass energy equivalent in MeV

type(codata_constant), parameter, public :: ALPHA_PARTICLE_MASS_IN_U = &
codata_constant("alpha particle mass in u", &
4.001506179127_dp, 0.000000000063_dp, &
"u") !! alpha particle mass in u

type(codata_constant), parameter, public :: ALPHA_PARTICLE_MOLAR_MASS = &
codata_constant("alpha particle molar mass", &
4.0015061777e-3_dp, 0.0000000012e-3_dp, &
"kg mol^-1") !! alpha particle molar mass

type(codata_constant), parameter, public :: ALPHA_PARTICLE_PROTON_MASS_RATIO = &
codata_constant("alpha particle-proton mass ratio", &
3.97259969009_dp, 0.00000000022_dp, &
"") !! alpha particle-proton mass ratio

type(codata_constant), parameter, public :: ALPHA_PARTICLE_RELATIVE_ATOMIC_MASS = &
codata_constant("alpha particle relative atomic mass", &
4.001506179127_dp, 0.000000000063_dp, &
"") !! alpha particle relative atomic mass

type(codata_constant), parameter, public :: ANGSTROM_STAR = &
codata_constant("Angstrom star", &
1.00001495e-10_dp, 0.00000090e-10_dp, &
"m") !! Angstrom star

type(codata_constant), parameter, public :: ATOMIC_MASS_CONSTANT = &
codata_constant("atomic mass constant", &
1.66053906660e-27_dp, 0.00000000050e-27_dp, &
"kg") !! atomic mass constant

type(codata_constant), parameter, public :: ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT = &
codata_constant("atomic mass constant energy equivalent", &
1.49241808560e-10_dp, 0.00000000045e-10_dp, &
"J") !! atomic mass constant energy equivalent

type(codata_constant), parameter, public :: ATOMIC_MASS_CONSTANT_ENERGY_EQUIVALENT_IN_MEV = &
codata_constant("atomic mass constant energy equivalent in MeV", &
931.49410242_dp, 0.00000028_dp, &
"MeV") !! atomic mass constant energy equivalent in MeV

type(codata_constant), parameter, public :: ATOMIC_MASS_UNIT_ELECTRON_VOLT_RELATIONSHIP = &
codata_constant("atomic mass unit-electron volt relationship", &
9.3149410242e8_dp, 0.0000000028e8_dp, &
"eV") !! atomic mass unit-electron volt relationship

type(codata_constant), parameter, public :: ATOMIC_MASS_UNIT_HARTREE_RELATIONSHIP = &
codata_constant("atomic mass unit-hartree relationship", &
3.4231776874e7_dp, 0.0000000010e7_dp, &
"E_h") !! atomic mass unit-hartree relationship

type(codata_constant), parameter, public :: ATOMIC_MASS_UNIT_HERTZ_RELATIONSHIP = &
codata_constant("atomic mass unit-hertz relationship", &
2.25234271871e23_dp, 0.00000000068e23_dp, &
"Hz") !! atomic mass unit-hertz relationship

type(codata_constant), parameter, public :: ATOMIC_MASS_UNIT_INVERSE_METER_RELATIONSHIP = &
codata_constant("atomic mass unit-inverse meter relationship", &
7.5130066104e14_dp, 0.0000000023e14_dp, &
"m^-1") !! atomic mass unit-inverse meter relationship

type(codata_constant), parameter, public :: ATOMIC_MASS_UNIT_JOULE_RELATIONSHIP = &
codata_constant("atomic mass unit-joule relationship", &
1.49241808560e-10_dp, 0.00000000045e-10_dp, &
"J") !! atomic mass unit-joule relationship

type(codata_constant), parameter, public :: ATOMIC_MASS_UNIT_KELVIN_RELATIONSHIP = &
codata_constant("atomic mass unit-kelvin relationship", &
1.08095401916e13_dp, 0.00000000033e13_dp, &
"K") !! atomic mass unit-kelvin relationship

type(codata_constant), parameter, public :: ATOMIC_MASS_UNIT_KILOGRAM_RELATIONSHIP = &
codata_constant("atomic mass unit-kilogram relationship", &
1.66053906660e-27_dp, 0.00000000050e-27_dp, &
"kg") !! atomic mass unit-kilogram relationship

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_1ST_HYPERPOLARIZABILITY = &
codata_constant("atomic unit of 1st hyperpolarizability", &
3.2063613061e-53_dp, 0.0000000015e-53_dp, &
"C^3 m^3 J^-2") !! atomic unit of 1st hyperpolarizability

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_2ND_HYPERPOLARIZABILITY = &
codata_constant("atomic unit of 2nd hyperpolarizability", &
6.2353799905e-65_dp, 0.0000000038e-65_dp, &
"C^4 m^4 J^-3") !! atomic unit of 2nd hyperpolarizability

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_ACTION = &
codata_constant("atomic unit of action", &
1.054571817e-34_dp, 0.0_dp, &
"J s") !! atomic unit of action

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_CHARGE = &
codata_constant("atomic unit of charge", &
1.602176634e-19_dp, 0.0_dp, &
"C") !! atomic unit of charge

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_CHARGE_DENSITY = &
codata_constant("atomic unit of charge density", &
1.08120238457e12_dp, 0.00000000049e12_dp, &
"C m^-3") !! atomic unit of charge density

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_CURRENT = &
codata_constant("atomic unit of current", &
6.623618237510e-3_dp, 0.000000000013e-3_dp, &
"A") !! atomic unit of current

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_ELECTRIC_DIPOLE_MOM = &
codata_constant("atomic unit of electric dipole mom.", &
8.4783536255e-30_dp, 0.0000000013e-30_dp, &
"C m") !! atomic unit of electric dipole mom.

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_ELECTRIC_FIELD = &
codata_constant("atomic unit of electric field", &
5.14220674763e11_dp, 0.00000000078e11_dp, &
"V m^-1") !! atomic unit of electric field

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_ELECTRIC_FIELD_GRADIENT = &
codata_constant("atomic unit of electric field gradient", &
9.7173624292e21_dp, 0.0000000029e21_dp, &
"V m^-2") !! atomic unit of electric field gradient

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_ELECTRIC_POLARIZABILITY = &
codata_constant("atomic unit of electric polarizability", &
1.64877727436e-41_dp, 0.00000000050e-41_dp, &
"C^2 m^2 J^-1") !! atomic unit of electric polarizability

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_ELECTRIC_POTENTIAL = &
codata_constant("atomic unit of electric potential", &
27.211386245988_dp, 0.000000000053_dp, &
"V") !! atomic unit of electric potential

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_ELECTRIC_QUADRUPOLE_MOM = &
codata_constant("atomic unit of electric quadrupole mom.", &
4.4865515246e-40_dp, 0.0000000014e-40_dp, &
"C m^2") !! atomic unit of electric quadrupole mom.

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_ENERGY = &
codata_constant("atomic unit of energy", &
4.3597447222071e-18_dp, 0.0000000000085e-18_dp, &
"J") !! atomic unit of energy

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_FORCE = &
codata_constant("atomic unit of force", &
8.2387234983e-8_dp, 0.0000000012e-8_dp, &
"N") !! atomic unit of force

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_LENGTH = &
codata_constant("atomic unit of length", &
5.29177210903e-11_dp, 0.00000000080e-11_dp, &
"m") !! atomic unit of length

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_MAG_DIPOLE_MOM = &
codata_constant("atomic unit of mag. dipole mom.", &
1.85480201566e-23_dp, 0.00000000056e-23_dp, &
"J T^-1") !! atomic unit of mag. dipole mom.

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_MAG_FLUX_DENSITY = &
codata_constant("atomic unit of mag. flux density", &
2.35051756758e5_dp, 0.00000000071e5_dp, &
"T") !! atomic unit of mag. flux density

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_MAGNETIZABILITY = &
codata_constant("atomic unit of magnetizability", &
7.8910366008e-29_dp, 0.0000000048e-29_dp, &
"J T^-2") !! atomic unit of magnetizability

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_MASS = &
codata_constant("atomic unit of mass", &
9.1093837015e-31_dp, 0.0000000028e-31_dp, &
"kg") !! atomic unit of mass

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_MOMENTUM = &
codata_constant("atomic unit of momentum", &
1.99285191410e-24_dp, 0.00000000030e-24_dp, &
"kg m s^-1") !! atomic unit of momentum

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_PERMITTIVITY = &
codata_constant("atomic unit of permittivity", &
1.11265005545e-10_dp, 0.00000000017e-10_dp, &
"F m^-1") !! atomic unit of permittivity

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_TIME = &
codata_constant("atomic unit of time", &
2.4188843265857e-17_dp, 0.0000000000047e-17_dp, &
"s") !! atomic unit of time

type(codata_constant), parameter, public :: ATOMIC_UNIT_OF_VELOCITY = &
codata_constant("atomic unit of velocity", &
2.18769126364e6_dp, 0.00000000033e6_dp, &
"m s^-1") !! atomic unit of velocity

type(codata_constant), parameter, public :: AVOGADRO_CONSTANT = &
codata_constant("Avogadro constant", &
6.02214076e23_dp, 0.0_dp, &
"mol^-1") !! Avogadro constant

type(codata_constant), parameter, public :: BOHR_MAGNETON = &
codata_constant("Bohr magneton", &
9.2740100783e-24_dp, 0.0000000028e-24_dp, &
"J T^-1") !! Bohr magneton

type(codata_constant), parameter, public :: BOHR_MAGNETON_IN_EV_T = &
codata_constant("Bohr magneton in eV/T", &
5.7883818060e-5_dp, 0.0000000017e-5_dp, &
"eV T^-1") !! Bohr magneton in eV/T

type(codata_constant), parameter, public :: BOHR_MAGNETON_IN_HZ_T = &
codata_constant("Bohr magneton in Hz/T", &
1.39962449361e10_dp, 0.00000000042e10_dp, &
"Hz T^-1") !! Bohr magneton in Hz/T

type(codata_constant), parameter, public :: BOHR_MAGNETON_IN_INVERSE_METER_PER_TESLA = &
codata_constant("Bohr magneton in inverse meter per tesla", &
46.686447783_dp, 0.000000014_dp, &
"m^-1 T^-1") !! Bohr magneton in inverse meter per tesla

type(codata_constant), parameter, public :: BOHR_MAGNETON_IN_K_T = &
codata_constant("Bohr magneton in K/T", &
0.67171381563_dp, 0.00000000020_dp, &
"K T^-1") !! Bohr magneton in K/T

type(codata_constant), parameter, public :: BOHR_RADIUS = &
codata_constant("Bohr radius", &
5.29177210903e-11_dp, 0.00000000080e-11_dp, &
"m") !! Bohr radius

type(codata_constant), parameter, public :: BOLTZMANN_CONSTANT = &
codata_constant("Boltzmann constant", &
1.380649e-23_dp, 0.0_dp, &
"J K^-1") !! Boltzmann constant

type(codata_constant), parameter, public :: BOLTZMANN_CONSTANT_IN_EV_K = &
codata_constant("Boltzmann constant in eV/K", &
8.617333262e-5_dp, 0.0_dp, &
"eV K^-1") !! Boltzmann constant in eV/K

type(codata_constant), parameter, public :: BOLTZMANN_CONSTANT_IN_HZ_K = &
codata_constant("Boltzmann constant in Hz/K", &
2.083661912e10_dp, 0.0_dp, &
"Hz K^-1") !! Boltzmann constant in Hz/K

type(codata_constant), parameter, public :: BOLTZMANN_CONSTANT_IN_INVERSE_METER_PER_KELVIN = &
codata_constant("Boltzmann constant in inverse meter per kelvin", &
69.50348004_dp, 0.0_dp, &
"m^-1 K^-1") !! Boltzmann constant in inverse meter per kelvin

type(codata_constant), parameter, public :: CHARACTERISTIC_IMPEDANCE_OF_VACUUM = &
codata_constant("characteristic impedance of vacuum", &
376.730313668_dp, 0.000000057_dp, &
"ohm") !! characteristic impedance of vacuum

type(codata_constant), parameter, public :: CLASSICAL_ELECTRON_RADIUS = &
codata_constant("classical electron radius", &
2.8179403262e-15_dp, 0.0000000013e-15_dp, &
"m") !! classical electron radius

type(codata_constant), parameter, public :: COMPTON_WAVELENGTH = &
codata_constant("Compton wavelength", &
2.42631023867e-12_dp, 0.00000000073e-12_dp, &
"m") !! Compton wavelength

type(codata_constant), parameter, public :: CONDUCTANCE_QUANTUM = &
codata_constant("conductance quantum", &
7.748091729e-5_dp, 0.0_dp, &
"S") !! conductance quantum

type(codata_constant), parameter, public :: CONVENTIONAL_VALUE_OF_AMPERE_90 = &
codata_constant("conventional value of ampere-90", &
1.00000008887_dp, 0.0_dp, &
"A") !! conventional value of ampere-90

type(codata_constant), parameter, public :: CONVENTIONAL_VALUE_OF_COULOMB_90 = &
codata_constant("conventional value of coulomb-90", &
1.00000008887_dp, 0.0_dp, &
"C") !! conventional value of coulomb-90

type(codata_constant), parameter, public :: CONVENTIONAL_VALUE_OF_FARAD_90 = &
codata_constant("conventional value of farad-90", &
0.99999998220_dp, 0.0_dp, &
"F") !! conventional value of farad-90

type(codata_constant), parameter, public :: CONVENTIONAL_VALUE_OF_HENRY_90 = &
codata_constant("conventional value of henry-90", &
1.00000001779_dp, 0.0_dp, &
"H") !! conventional value of henry-90

type(codata_constant), parameter, public :: CONVENTIONAL_VALUE_OF_JOSEPHSON_CONSTANT = &
codata_constant("conventional value of Josephson constant", &
483597.9e9_dp, 0.0_dp, &
"Hz V^-1") !! conventional value of Josephson constant

type(codata_constant), parameter, public :: CONVENTIONAL_VALUE_OF_OHM_90 = &
codata_constant("conventional value of ohm-90", &
1.00000001779_dp, 0.0_dp, &
"ohm") !! conventional value of ohm-90

type(codata_constant), parameter, public :: CONVENTIONAL_VALUE_OF_VOLT_90 = &
codata_constant("conventional value of volt-90", &
1.00000010666_dp, 0.0_dp, &
"V") !! conventional value of volt-90

type(codata_constant), parameter, public :: CONVENTIONAL_VALUE_OF_VON_KLITZING_CONSTANT = &
codata_constant("conventional value of von Klitzing constant", &
25812.807_dp, 0.0_dp, &
"ohm") !! conventional value of von Klitzing constant

type(codata_constant), parameter, public :: CONVENTIONAL_VALUE_OF_WATT_90 = &
codata_constant("conventional value of watt-90", &
1.00000019553_dp, 0.0_dp, &
"W") !! conventional value of watt-90

type(codata_constant), parameter, public :: COPPER_X_UNIT = &
codata_constant("Copper x unit", &
1.00207697e-13_dp, 0.00000028e-13_dp, &
"m") !! Copper x unit

type(codata_constant), parameter, public :: DEUTERON_ELECTRON_MAG_MOM_RATIO = &
codata_constant("deuteron-electron mag. mom. ratio", &
-4.664345551e-4_dp, 0.000000012e-4_dp, &
"") !! deuteron-electron mag. mom. ratio

type(codata_constant), parameter, public :: DEUTERON_ELECTRON_MASS_RATIO = &
codata_constant("deuteron-electron mass ratio", &
3670.48296788_dp, 0.00000013_dp, &
"") !! deuteron-electron mass ratio

type(codata_constant), parameter, public :: DEUTERON_G_FACTOR = &
codata_constant("deuteron g factor", &
0.8574382338_dp, 0.0000000022_dp, &
"") !! deuteron g factor

type(codata_constant), parameter, public :: DEUTERON_MAG_MOM = &
codata_constant("deuteron mag. mom.", &
4.330735094e-27_dp, 0.000000011e-27_dp, &
"J T^-1") !! deuteron mag. mom.

type(codata_constant), parameter, public :: DEUTERON_MAG_MOM_TO_BOHR_MAGNETON_RATIO = &
codata_constant("deuteron mag. mom. to Bohr magneton ratio", &
4.669754570e-4_dp, 0.000000012e-4_dp, &
"") !! deuteron mag. mom. to Bohr magneton ratio

type(codata_constant), parameter, public :: DEUTERON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO = &
codata_constant("deuteron mag. mom. to nuclear magneton ratio", &
0.8574382338_dp, 0.0000000022_dp, &
"") !! deuteron mag. mom. to nuclear magneton ratio

type(codata_constant), parameter, public :: DEUTERON_MASS = &
codata_constant("deuteron mass", &
3.3435837724e-27_dp, 0.0000000010e-27_dp, &
"kg") !! deuteron mass

type(codata_constant), parameter, public :: DEUTERON_MASS_ENERGY_EQUIVALENT = &
codata_constant("deuteron mass energy equivalent", &
3.00506323102e-10_dp, 0.00000000091e-10_dp, &
"J") !! deuteron mass energy equivalent

type(codata_constant), parameter, public :: DEUTERON_MASS_ENERGY_EQUIVALENT_IN_MEV = &
codata_constant("deuteron mass energy equivalent in MeV", &
1875.61294257_dp, 0.00000057_dp, &
"MeV") !! deuteron mass energy equivalent in MeV

type(codata_constant), parameter, public :: DEUTERON_MASS_IN_U = &
codata_constant("deuteron mass in u", &
2.013553212745_dp, 0.000000000040_dp, &
"u") !! deuteron mass in u

type(codata_constant), parameter, public :: DEUTERON_MOLAR_MASS = &
codata_constant("deuteron molar mass", &
2.01355321205e-3_dp, 0.00000000061e-3_dp, &
"kg mol^-1") !! deuteron molar mass

type(codata_constant), parameter, public :: DEUTERON_NEUTRON_MAG_MOM_RATIO = &
codata_constant("deuteron-neutron mag. mom. ratio", &
-0.44820653_dp, 0.00000011_dp, &
"") !! deuteron-neutron mag. mom. ratio

type(codata_constant), parameter, public :: DEUTERON_PROTON_MAG_MOM_RATIO = &
codata_constant("deuteron-proton mag. mom. ratio", &
0.30701220939_dp, 0.00000000079_dp, &
"") !! deuteron-proton mag. mom. ratio

type(codata_constant), parameter, public :: DEUTERON_PROTON_MASS_RATIO = &
codata_constant("deuteron-proton mass ratio", &
1.99900750139_dp, 0.00000000011_dp, &
"") !! deuteron-proton mass ratio

type(codata_constant), parameter, public :: DEUTERON_RELATIVE_ATOMIC_MASS = &
codata_constant("deuteron relative atomic mass", &
2.013553212745_dp, 0.000000000040_dp, &
"") !! deuteron relative atomic mass

type(codata_constant), parameter, public :: DEUTERON_RMS_CHARGE_RADIUS = &
codata_constant("deuteron rms charge radius", &
2.12799e-15_dp, 0.00074e-15_dp, &
"m") !! deuteron rms charge radius

type(codata_constant), parameter, public :: ELECTRON_CHARGE_TO_MASS_QUOTIENT = &
codata_constant("electron charge to mass quotient", &
-1.75882001076e11_dp, 0.00000000053e11_dp, &
"C kg^-1") !! electron charge to mass quotient

type(codata_constant), parameter, public :: ELECTRON_DEUTERON_MAG_MOM_RATIO = &
codata_constant("electron-deuteron mag. mom. ratio", &
-2143.9234915_dp, 0.0000056_dp, &
"") !! electron-deuteron mag. mom. ratio

type(codata_constant), parameter, public :: ELECTRON_DEUTERON_MASS_RATIO = &
codata_constant("electron-deuteron mass ratio", &
2.724437107462e-4_dp, 0.000000000096e-4_dp, &
"") !! electron-deuteron mass ratio

type(codata_constant), parameter, public :: ELECTRON_G_FACTOR = &
codata_constant("electron g factor", &
-2.00231930436256_dp, 0.00000000000035_dp, &
"") !! electron g factor

type(codata_constant), parameter, public :: ELECTRON_GYROMAG_RATIO = &
codata_constant("electron gyromag. ratio", &
1.76085963023e11_dp, 0.00000000053e11_dp, &
"s^-1 T^-1") !! electron gyromag. ratio

type(codata_constant), parameter, public :: ELECTRON_GYROMAG_RATIO_IN_MHZ_T = &
codata_constant("electron gyromag. ratio in MHz/T", &
28024.9514242_dp, 0.0000085_dp, &
"MHz T^-1") !! electron gyromag. ratio in MHz/T

type(codata_constant), parameter, public :: ELECTRON_HELION_MASS_RATIO = &
codata_constant("electron-helion mass ratio", &
1.819543074573e-4_dp, 0.000000000079e-4_dp, &
"") !! electron-helion mass ratio

type(codata_constant), parameter, public :: ELECTRON_MAG_MOM = &
codata_constant("electron mag. mom.", &
-9.2847647043e-24_dp, 0.0000000028e-24_dp, &
"J T^-1") !! electron mag. mom.

type(codata_constant), parameter, public :: ELECTRON_MAG_MOM_ANOMALY = &
codata_constant("electron mag. mom. anomaly", &
1.15965218128e-3_dp, 0.00000000018e-3_dp, &
"") !! electron mag. mom. anomaly

type(codata_constant), parameter, public :: ELECTRON_MAG_MOM_TO_BOHR_MAGNETON_RATIO = &
codata_constant("electron mag. mom. to Bohr magneton ratio", &
-1.00115965218128_dp, 0.00000000000018_dp, &
"") !! electron mag. mom. to Bohr magneton ratio

type(codata_constant), parameter, public :: ELECTRON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO = &
codata_constant("electron mag. mom. to nuclear magneton ratio", &
-1838.28197188_dp, 0.00000011_dp, &
"") !! electron mag. mom. to nuclear magneton ratio

type(codata_constant), parameter, public :: ELECTRON_MASS = &
codata_constant("electron mass", &
9.1093837015e-31_dp, 0.0000000028e-31_dp, &
"kg") !! electron mass

type(codata_constant), parameter, public :: ELECTRON_MASS_ENERGY_EQUIVALENT = &
codata_constant("electron mass energy equivalent", &
8.1871057769e-14_dp, 0.0000000025e-14_dp, &
"J") !! electron mass energy equivalent

type(codata_constant), parameter, public :: ELECTRON_MASS_ENERGY_EQUIVALENT_IN_MEV = &
codata_constant("electron mass energy equivalent in MeV", &
0.51099895000_dp, 0.00000000015_dp, &
"MeV") !! electron mass energy equivalent in MeV

type(codata_constant), parameter, public :: ELECTRON_MASS_IN_U = &
codata_constant("electron mass in u", &
5.48579909065e-4_dp, 0.00000000016e-4_dp, &
"u") !! electron mass in u

type(codata_constant), parameter, public :: ELECTRON_MOLAR_MASS = &
codata_constant("electron molar mass", &
5.4857990888e-7_dp, 0.0000000017e-7_dp, &
"kg mol^-1") !! electron molar mass

type(codata_constant), parameter, public :: ELECTRON_MUON_MAG_MOM_RATIO = &
codata_constant("electron-muon mag. mom. ratio", &
206.7669883_dp, 0.0000046_dp, &
"") !! electron-muon mag. mom. ratio

type(codata_constant), parameter, public :: ELECTRON_MUON_MASS_RATIO = &
codata_constant("electron-muon mass ratio", &
4.83633169e-3_dp, 0.00000011e-3_dp, &
"") !! electron-muon mass ratio

type(codata_constant), parameter, public :: ELECTRON_NEUTRON_MAG_MOM_RATIO = &
codata_constant("electron-neutron mag. mom. ratio", &
960.92050_dp, 0.00023_dp, &
"") !! electron-neutron mag. mom. ratio

type(codata_constant), parameter, public :: ELECTRON_NEUTRON_MASS_RATIO = &
codata_constant("electron-neutron mass ratio", &
5.4386734424e-4_dp, 0.0000000026e-4_dp, &
"") !! electron-neutron mass ratio

type(codata_constant), parameter, public :: ELECTRON_PROTON_MAG_MOM_RATIO = &
codata_constant("electron-proton mag. mom. ratio", &
-658.21068789_dp, 0.00000020_dp, &
"") !! electron-proton mag. mom. ratio

type(codata_constant), parameter, public :: ELECTRON_PROTON_MASS_RATIO = &
codata_constant("electron-proton mass ratio", &
5.44617021487e-4_dp, 0.00000000033e-4_dp, &
"") !! electron-proton mass ratio

type(codata_constant), parameter, public :: ELECTRON_RELATIVE_ATOMIC_MASS = &
codata_constant("electron relative atomic mass", &
5.48579909065e-4_dp, 0.00000000016e-4_dp, &
"") !! electron relative atomic mass

type(codata_constant), parameter, public :: ELECTRON_TAU_MASS_RATIO = &
codata_constant("electron-tau mass ratio", &
2.87585e-4_dp, 0.00019e-4_dp, &
"") !! electron-tau mass ratio

type(codata_constant), parameter, public :: ELECTRON_TO_ALPHA_PARTICLE_MASS_RATIO = &
codata_constant("electron to alpha particle mass ratio", &
1.370933554787e-4_dp, 0.000000000045e-4_dp, &
"") !! electron to alpha particle mass ratio

type(codata_constant), parameter, public :: ELECTRON_TO_SHIELDED_HELION_MAG_MOM_RATIO = &
codata_constant("electron to shielded helion mag. mom. ratio", &
864.058257_dp, 0.000010_dp, &
"") !! electron to shielded helion mag. mom. ratio

type(codata_constant), parameter, public :: ELECTRON_TO_SHIELDED_PROTON_MAG_MOM_RATIO = &
codata_constant("electron to shielded proton mag. mom. ratio", &
-658.2275971_dp, 0.0000072_dp, &
"") !! electron to shielded proton mag. mom. ratio

type(codata_constant), parameter, public :: ELECTRON_TRITON_MASS_RATIO = &
codata_constant("electron-triton mass ratio", &
1.819200062251e-4_dp, 0.000000000090e-4_dp, &
"") !! electron-triton mass ratio

type(codata_constant), parameter, public :: ELECTRON_VOLT = &
codata_constant("electron volt", &
1.602176634e-19_dp, 0.0_dp, &
"J") !! electron volt

type(codata_constant), parameter, public :: ELECTRON_VOLT_ATOMIC_MASS_UNIT_RELATIONSHIP = &
codata_constant("electron volt-atomic mass unit relationship", &
1.07354410233e-9_dp, 0.00000000032e-9_dp, &
"u") !! electron volt-atomic mass unit relationship

type(codata_constant), parameter, public :: ELECTRON_VOLT_HARTREE_RELATIONSHIP = &
codata_constant("electron volt-hartree relationship", &
3.6749322175655e-2_dp, 0.0000000000071e-2_dp, &
"E_h") !! electron volt-hartree relationship

type(codata_constant), parameter, public :: ELECTRON_VOLT_HERTZ_RELATIONSHIP = &
codata_constant("electron volt-hertz relationship", &
2.417989242e14_dp, 0.0_dp, &
"Hz") !! electron volt-hertz relationship

type(codata_constant), parameter, public :: ELECTRON_VOLT_INVERSE_METER_RELATIONSHIP = &
codata_constant("electron volt-inverse meter relationship", &
8.065543937e5_dp, 0.0_dp, &
"m^-1") !! electron volt-inverse meter relationship

type(codata_constant), parameter, public :: ELECTRON_VOLT_JOULE_RELATIONSHIP = &
codata_constant("electron volt-joule relationship", &
1.602176634e-19_dp, 0.0_dp, &
"J") !! electron volt-joule relationship

type(codata_constant), parameter, public :: ELECTRON_VOLT_KELVIN_RELATIONSHIP = &
codata_constant("electron volt-kelvin relationship", &
1.160451812e4_dp, 0.0_dp, &
"K") !! electron volt-kelvin relationship

type(codata_constant), parameter, public :: ELECTRON_VOLT_KILOGRAM_RELATIONSHIP = &
codata_constant("electron volt-kilogram relationship", &
1.782661921e-36_dp, 0.0_dp, &
"kg") !! electron volt-kilogram relationship

type(codata_constant), parameter, public :: ELEMENTARY_CHARGE = &
codata_constant("elementary charge", &
1.602176634e-19_dp, 0.0_dp, &
"C") !! elementary charge

type(codata_constant), parameter, public :: ELEMENTARY_CHARGE_OVER_H_BAR = &
codata_constant("elementary charge over h-bar", &
1.519267447e15_dp, 0.0_dp, &
"A J^-1") !! elementary charge over h-bar

type(codata_constant), parameter, public :: FARADAY_CONSTANT = &
codata_constant("Faraday constant", &
96485.33212_dp, 0.0_dp, &
"C mol^-1") !! Faraday constant

type(codata_constant), parameter, public :: FERMI_COUPLING_CONSTANT = &
codata_constant("Fermi coupling constant", &
1.1663787e-5_dp, 0.0000006e-5_dp, &
"GeV^-2") !! Fermi coupling constant

type(codata_constant), parameter, public :: FINE_STRUCTURE_CONSTANT = &
codata_constant("fine-structure constant", &
7.2973525693e-3_dp, 0.0000000011e-3_dp, &
"") !! fine-structure constant

type(codata_constant), parameter, public :: FIRST_RADIATION_CONSTANT = &
codata_constant("first radiation constant", &
3.741771852e-16_dp, 0.0_dp, &
"W m^2") !! first radiation constant

type(codata_constant), parameter, public :: FIRST_RADIATION_CONSTANT_FOR_SPECTRAL_RADIANCE = &
codata_constant("first radiation constant for spectral radiance", &
1.191042972e-16_dp, 0.0_dp, &
"W m^2 sr^-1") !! first radiation constant for spectral radiance

type(codata_constant), parameter, public :: HARTREE_ATOMIC_MASS_UNIT_RELATIONSHIP = &
codata_constant("hartree-atomic mass unit relationship", &
2.92126232205e-8_dp, 0.00000000088e-8_dp, &
"u") !! hartree-atomic mass unit relationship

type(codata_constant), parameter, public :: HARTREE_ELECTRON_VOLT_RELATIONSHIP = &
codata_constant("hartree-electron volt relationship", &
27.211386245988_dp, 0.000000000053_dp, &
"eV") !! hartree-electron volt relationship

type(codata_constant), parameter, public :: HARTREE_ENERGY = &
codata_constant("Hartree energy", &
4.3597447222071e-18_dp, 0.0000000000085e-18_dp, &
"J") !! Hartree energy

type(codata_constant), parameter, public :: HARTREE_ENERGY_IN_EV = &
codata_constant("Hartree energy in eV", &
27.211386245988_dp, 0.000000000053_dp, &
"eV") !! Hartree energy in eV

type(codata_constant), parameter, public :: HARTREE_HERTZ_RELATIONSHIP = &
codata_constant("hartree-hertz relationship", &
6.579683920502e15_dp, 0.000000000013e15_dp, &
"Hz") !! hartree-hertz relationship

type(codata_constant), parameter, public :: HARTREE_INVERSE_METER_RELATIONSHIP = &
codata_constant("hartree-inverse meter relationship", &
2.1947463136320e7_dp, 0.0000000000043e7_dp, &
"m^-1") !! hartree-inverse meter relationship

type(codata_constant), parameter, public :: HARTREE_JOULE_RELATIONSHIP = &
codata_constant("hartree-joule relationship", &
4.3597447222071e-18_dp, 0.0000000000085e-18_dp, &
"J") !! hartree-joule relationship

type(codata_constant), parameter, public :: HARTREE_KELVIN_RELATIONSHIP = &
codata_constant("hartree-kelvin relationship", &
3.1577502480407e5_dp, 0.0000000000061e5_dp, &
"K") !! hartree-kelvin relationship

type(codata_constant), parameter, public :: HARTREE_KILOGRAM_RELATIONSHIP = &
codata_constant("hartree-kilogram relationship", &
4.8508702095432e-35_dp, 0.0000000000094e-35_dp, &
"kg") !! hartree-kilogram relationship

type(codata_constant), parameter, public :: HELION_ELECTRON_MASS_RATIO = &
codata_constant("helion-electron mass ratio", &
5495.88528007_dp, 0.00000024_dp, &
"") !! helion-electron mass ratio

type(codata_constant), parameter, public :: HELION_G_FACTOR = &
codata_constant("helion g factor", &
-4.255250615_dp, 0.000000050_dp, &
"") !! helion g factor

type(codata_constant), parameter, public :: HELION_MAG_MOM = &
codata_constant("helion mag. mom.", &
-1.074617532e-26_dp, 0.000000013e-26_dp, &
"J T^-1") !! helion mag. mom.

type(codata_constant), parameter, public :: HELION_MAG_MOM_TO_BOHR_MAGNETON_RATIO = &
codata_constant("helion mag. mom. to Bohr magneton ratio", &
-1.158740958e-3_dp, 0.000000014e-3_dp, &
"") !! helion mag. mom. to Bohr magneton ratio

type(codata_constant), parameter, public :: HELION_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO = &
codata_constant("helion mag. mom. to nuclear magneton ratio", &
-2.127625307_dp, 0.000000025_dp, &
"") !! helion mag. mom. to nuclear magneton ratio

type(codata_constant), parameter, public :: HELION_MASS = &
codata_constant("helion mass", &
5.0064127796e-27_dp, 0.0000000015e-27_dp, &
"kg") !! helion mass

type(codata_constant), parameter, public :: HELION_MASS_ENERGY_EQUIVALENT = &
codata_constant("helion mass energy equivalent", &
4.4995394125e-10_dp, 0.0000000014e-10_dp, &
"J") !! helion mass energy equivalent

type(codata_constant), parameter, public :: HELION_MASS_ENERGY_EQUIVALENT_IN_MEV = &
codata_constant("helion mass energy equivalent in MeV", &
2808.39160743_dp, 0.00000085_dp, &
"MeV") !! helion mass energy equivalent in MeV

type(codata_constant), parameter, public :: HELION_MASS_IN_U = &
codata_constant("helion mass in u", &
3.014932247175_dp, 0.000000000097_dp, &
"u") !! helion mass in u

type(codata_constant), parameter, public :: HELION_MOLAR_MASS = &
codata_constant("helion molar mass", &
3.01493224613e-3_dp, 0.00000000091e-3_dp, &
"kg mol^-1") !! helion molar mass

type(codata_constant), parameter, public :: HELION_PROTON_MASS_RATIO = &
codata_constant("helion-proton mass ratio", &
2.99315267167_dp, 0.00000000013_dp, &
"") !! helion-proton mass ratio

type(codata_constant), parameter, public :: HELION_RELATIVE_ATOMIC_MASS = &
codata_constant("helion relative atomic mass", &
3.014932247175_dp, 0.000000000097_dp, &
"") !! helion relative atomic mass

type(codata_constant), parameter, public :: HELION_SHIELDING_SHIFT = &
codata_constant("helion shielding shift", &
5.996743e-5_dp, 0.000010e-5_dp, &
"") !! helion shielding shift

type(codata_constant), parameter, public :: HERTZ_ATOMIC_MASS_UNIT_RELATIONSHIP = &
codata_constant("hertz-atomic mass unit relationship", &
4.4398216652e-24_dp, 0.0000000013e-24_dp, &
"u") !! hertz-atomic mass unit relationship

type(codata_constant), parameter, public :: HERTZ_ELECTRON_VOLT_RELATIONSHIP = &
codata_constant("hertz-electron volt relationship", &
4.135667696e-15_dp, 0.0_dp, &
"eV") !! hertz-electron volt relationship

type(codata_constant), parameter, public :: HERTZ_HARTREE_RELATIONSHIP = &
codata_constant("hertz-hartree relationship", &
1.5198298460570e-16_dp, 0.0000000000029e-16_dp, &
"E_h") !! hertz-hartree relationship

type(codata_constant), parameter, public :: HERTZ_INVERSE_METER_RELATIONSHIP = &
codata_constant("hertz-inverse meter relationship", &
3.335640951e-9_dp, 0.0_dp, &
"m^-1") !! hertz-inverse meter relationship

type(codata_constant), parameter, public :: HERTZ_JOULE_RELATIONSHIP = &
codata_constant("hertz-joule relationship", &
6.62607015e-34_dp, 0.0_dp, &
"J") !! hertz-joule relationship

type(codata_constant), parameter, public :: HERTZ_KELVIN_RELATIONSHIP = &
codata_constant("hertz-kelvin relationship", &
4.799243073e-11_dp, 0.0_dp, &
"K") !! hertz-kelvin relationship

type(codata_constant), parameter, public :: HERTZ_KILOGRAM_RELATIONSHIP = &
codata_constant("hertz-kilogram relationship", &
7.372497323e-51_dp, 0.0_dp, &
"kg") !! hertz-kilogram relationship

type(codata_constant), parameter, public :: HYPERFINE_TRANSITION_FREQUENCY_OF_CS_133 = &
codata_constant("hyperfine transition frequency of Cs-133", &
9192631770_dp, 0.0_dp, &
"Hz") !! hyperfine transition frequency of Cs-133

type(codata_constant), parameter, public :: INVERSE_FINE_STRUCTURE_CONSTANT = &
codata_constant("inverse fine-structure constant", &
137.035999084_dp, 0.000000021_dp, &
"") !! inverse fine-structure constant

type(codata_constant), parameter, public :: INVERSE_METER_ATOMIC_MASS_UNIT_RELATIONSHIP = &
codata_constant("inverse meter-atomic mass unit relationship", &
1.33102505010e-15_dp, 0.00000000040e-15_dp, &
"u") !! inverse meter-atomic mass unit relationship

type(codata_constant), parameter, public :: INVERSE_METER_ELECTRON_VOLT_RELATIONSHIP = &
codata_constant("inverse meter-electron volt relationship", &
1.239841984e-6_dp, 0.0_dp, &
"eV") !! inverse meter-electron volt relationship

type(codata_constant), parameter, public :: INVERSE_METER_HARTREE_RELATIONSHIP = &
codata_constant("inverse meter-hartree relationship", &
4.5563352529120e-8_dp, 0.0000000000088e-8_dp, &
"E_h") !! inverse meter-hartree relationship

type(codata_constant), parameter, public :: INVERSE_METER_HERTZ_RELATIONSHIP = &
codata_constant("inverse meter-hertz relationship", &
299792458_dp, 0.0_dp, &
"Hz") !! inverse meter-hertz relationship

type(codata_constant), parameter, public :: INVERSE_METER_JOULE_RELATIONSHIP = &
codata_constant("inverse meter-joule relationship", &
1.986445857e-25_dp, 0.0_dp, &
"J") !! inverse meter-joule relationship

type(codata_constant), parameter, public :: INVERSE_METER_KELVIN_RELATIONSHIP = &
codata_constant("inverse meter-kelvin relationship", &
1.438776877e-2_dp, 0.0_dp, &
"K") !! inverse meter-kelvin relationship

type(codata_constant), parameter, public :: INVERSE_METER_KILOGRAM_RELATIONSHIP = &
codata_constant("inverse meter-kilogram relationship", &
2.210219094e-42_dp, 0.0_dp, &
"kg") !! inverse meter-kilogram relationship

type(codata_constant), parameter, public :: INVERSE_OF_CONDUCTANCE_QUANTUM = &
codata_constant("inverse of conductance quantum", &
12906.40372_dp, 0.0_dp, &
"ohm") !! inverse of conductance quantum

type(codata_constant), parameter, public :: JOSEPHSON_CONSTANT = &
codata_constant("Josephson constant", &
483597.8484e9_dp, 0.0_dp, &
"Hz V^-1") !! Josephson constant

type(codata_constant), parameter, public :: JOULE_ATOMIC_MASS_UNIT_RELATIONSHIP = &
codata_constant("joule-atomic mass unit relationship", &
6.7005352565e9_dp, 0.0000000020e9_dp, &
"u") !! joule-atomic mass unit relationship

type(codata_constant), parameter, public :: JOULE_ELECTRON_VOLT_RELATIONSHIP = &
codata_constant("joule-electron volt relationship", &
6.241509074e18_dp, 0.0_dp, &
"eV") !! joule-electron volt relationship

type(codata_constant), parameter, public :: JOULE_HARTREE_RELATIONSHIP = &
codata_constant("joule-hartree relationship", &
2.2937122783963e17_dp, 0.0000000000045e17_dp, &
"E_h") !! joule-hartree relationship

type(codata_constant), parameter, public :: JOULE_HERTZ_RELATIONSHIP = &
codata_constant("joule-hertz relationship", &
1.509190179e33_dp, 0.0_dp, &
"Hz") !! joule-hertz relationship

type(codata_constant), parameter, public :: JOULE_INVERSE_METER_RELATIONSHIP = &
codata_constant("joule-inverse meter relationship", &
5.034116567e24_dp, 0.0_dp, &
"m^-1") !! joule-inverse meter relationship

type(codata_constant), parameter, public :: JOULE_KELVIN_RELATIONSHIP = &
codata_constant("joule-kelvin relationship", &
7.242970516e22_dp, 0.0_dp, &
"K") !! joule-kelvin relationship

type(codata_constant), parameter, public :: JOULE_KILOGRAM_RELATIONSHIP = &
codata_constant("joule-kilogram relationship", &
1.112650056e-17_dp, 0.0_dp, &
"kg") !! joule-kilogram relationship

type(codata_constant), parameter, public :: KELVIN_ATOMIC_MASS_UNIT_RELATIONSHIP = &
codata_constant("kelvin-atomic mass unit relationship", &
9.2510873014e-14_dp, 0.0000000028e-14_dp, &
"u") !! kelvin-atomic mass unit relationship

type(codata_constant), parameter, public :: KELVIN_ELECTRON_VOLT_RELATIONSHIP = &
codata_constant("kelvin-electron volt relationship", &
8.617333262e-5_dp, 0.0_dp, &
"eV") !! kelvin-electron volt relationship

type(codata_constant), parameter, public :: KELVIN_HARTREE_RELATIONSHIP = &
codata_constant("kelvin-hartree relationship", &
3.1668115634556e-6_dp, 0.0000000000061e-6_dp, &
"E_h") !! kelvin-hartree relationship

type(codata_constant), parameter, public :: KELVIN_HERTZ_RELATIONSHIP = &
codata_constant("kelvin-hertz relationship", &
2.083661912e10_dp, 0.0_dp, &
"Hz") !! kelvin-hertz relationship

type(codata_constant), parameter, public :: KELVIN_INVERSE_METER_RELATIONSHIP = &
codata_constant("kelvin-inverse meter relationship", &
69.50348004_dp, 0.0_dp, &
"m^-1") !! kelvin-inverse meter relationship

type(codata_constant), parameter, public :: KELVIN_JOULE_RELATIONSHIP = &
codata_constant("kelvin-joule relationship", &
1.380649e-23_dp, 0.0_dp, &
"J") !! kelvin-joule relationship

type(codata_constant), parameter, public :: KELVIN_KILOGRAM_RELATIONSHIP = &
codata_constant("kelvin-kilogram relationship", &
1.536179187e-40_dp, 0.0_dp, &
"kg") !! kelvin-kilogram relationship

type(codata_constant), parameter, public :: KILOGRAM_ATOMIC_MASS_UNIT_RELATIONSHIP = &
codata_constant("kilogram-atomic mass unit relationship", &
6.0221407621e26_dp, 0.0000000018e26_dp, &
"u") !! kilogram-atomic mass unit relationship

type(codata_constant), parameter, public :: KILOGRAM_ELECTRON_VOLT_RELATIONSHIP = &
codata_constant("kilogram-electron volt relationship", &
5.609588603e35_dp, 0.0_dp, &
"eV") !! kilogram-electron volt relationship

type(codata_constant), parameter, public :: KILOGRAM_HARTREE_RELATIONSHIP = &
codata_constant("kilogram-hartree relationship", &
2.0614857887409e34_dp, 0.0000000000040e34_dp, &
"E_h") !! kilogram-hartree relationship

type(codata_constant), parameter, public :: KILOGRAM_HERTZ_RELATIONSHIP = &
codata_constant("kilogram-hertz relationship", &
1.356392489e50_dp, 0.0_dp, &
"Hz") !! kilogram-hertz relationship

type(codata_constant), parameter, public :: KILOGRAM_INVERSE_METER_RELATIONSHIP = &
codata_constant("kilogram-inverse meter relationship", &
4.524438335e41_dp, 0.0_dp, &
"m^-1") !! kilogram-inverse meter relationship

type(codata_constant), parameter, public :: KILOGRAM_JOULE_RELATIONSHIP = &
codata_constant("kilogram-joule relationship", &
8.987551787e16_dp, 0.0_dp, &
"J") !! kilogram-joule relationship

type(codata_constant), parameter, public :: KILOGRAM_KELVIN_RELATIONSHIP = &
codata_constant("kilogram-kelvin relationship", &
6.509657260e39_dp, 0.0_dp, &
"K") !! kilogram-kelvin relationship

type(codata_constant), parameter, public :: LATTICE_PARAMETER_OF_SILICON = &
codata_constant("lattice parameter of silicon", &
5.431020511e-10_dp, 0.000000089e-10_dp, &
"m") !! lattice parameter of silicon

type(codata_constant), parameter, public :: LATTICE_SPACING_OF_IDEAL_SI_220 = &
codata_constant("lattice spacing of ideal Si (220)", &
1.920155716e-10_dp, 0.000000032e-10_dp, &
"m") !! lattice spacing of ideal Si (220)

type(codata_constant), parameter, public :: LOSCHMIDT_CONSTANT_27315_K_100_KPA = &
codata_constant("Loschmidt constant (273.15 K, 100 kPa)", &
2.651645804e25_dp, 0.0_dp, &
"m^-3") !! Loschmidt constant (273.15 K, 100 kPa)

type(codata_constant), parameter, public :: LOSCHMIDT_CONSTANT_27315_K_101325_KPA = &
codata_constant("Loschmidt constant (273.15 K, 101.325 kPa)", &
2.686780111e25_dp, 0.0_dp, &
"m^-3") !! Loschmidt constant (273.15 K, 101.325 kPa)

type(codata_constant), parameter, public :: LUMINOUS_EFFICACY = &
codata_constant("luminous efficacy", &
683_dp, 0.0_dp, &
"lm W^-1") !! luminous efficacy

type(codata_constant), parameter, public :: MAG_FLUX_QUANTUM = &
codata_constant("mag. flux quantum", &
2.067833848e-15_dp, 0.0_dp, &
"Wb") !! mag. flux quantum

type(codata_constant), parameter, public :: MOLAR_GAS_CONSTANT = &
codata_constant("molar gas constant", &
8.314462618_dp, 0.0_dp, &
"J mol^-1 K^-1") !! molar gas constant

type(codata_constant), parameter, public :: MOLAR_MASS_CONSTANT = &
codata_constant("molar mass constant", &
0.99999999965e-3_dp, 0.00000000030e-3_dp, &
"kg mol^-1") !! molar mass constant

type(codata_constant), parameter, public :: MOLAR_MASS_OF_CARBON_12 = &
codata_constant("molar mass of carbon-12", &
11.9999999958e-3_dp, 0.0000000036e-3_dp, &
"kg mol^-1") !! molar mass of carbon-12

type(codata_constant), parameter, public :: MOLAR_PLANCK_CONSTANT = &
codata_constant("molar Planck constant", &
3.990312712e-10_dp, 0.0_dp, &
"J Hz^-1 mol^-1") !! molar Planck constant

type(codata_constant), parameter, public :: MOLAR_VOLUME_OF_IDEAL_GAS_27315_K_100_KPA = &
codata_constant("molar volume of ideal gas (273.15 K, 100 kPa)", &
22.71095464e-3_dp, 0.0_dp, &
"m^3 mol^-1") !! molar volume of ideal gas (273.15 K, 100 kPa)

type(codata_constant), parameter, public :: MOLAR_VOLUME_OF_IDEAL_GAS_27315_K_101325_KPA = &
codata_constant("molar volume of ideal gas (273.15 K, 101.325 kPa)", &
22.41396954e-3_dp, 0.0_dp, &
"m^3 mol^-1") !! molar volume of ideal gas (273.15 K, 101.325 kPa)

type(codata_constant), parameter, public :: MOLAR_VOLUME_OF_SILICON = &
codata_constant("molar volume of silicon", &
1.205883199e-5_dp, 0.000000060e-5_dp, &
"m^3 mol^-1") !! molar volume of silicon

type(codata_constant), parameter, public :: MOLYBDENUM_X_UNIT = &
codata_constant("Molybdenum x unit", &
1.00209952e-13_dp, 0.00000053e-13_dp, &
"m") !! Molybdenum x unit

type(codata_constant), parameter, public :: MUON_COMPTON_WAVELENGTH = &
codata_constant("muon Compton wavelength", &
1.173444110e-14_dp, 0.000000026e-14_dp, &
"m") !! muon Compton wavelength

type(codata_constant), parameter, public :: MUON_ELECTRON_MASS_RATIO = &
codata_constant("muon-electron mass ratio", &
206.7682830_dp, 0.0000046_dp, &
"") !! muon-electron mass ratio

type(codata_constant), parameter, public :: MUON_G_FACTOR = &
codata_constant("muon g factor", &
-2.0023318418_dp, 0.0000000013_dp, &
"") !! muon g factor

type(codata_constant), parameter, public :: MUON_MAG_MOM = &
codata_constant("muon mag. mom.", &
-4.49044830e-26_dp, 0.00000010e-26_dp, &
"J T^-1") !! muon mag. mom.

type(codata_constant), parameter, public :: MUON_MAG_MOM_ANOMALY = &
codata_constant("muon mag. mom. anomaly", &
1.16592089e-3_dp, 0.00000063e-3_dp, &
"") !! muon mag. mom. anomaly

type(codata_constant), parameter, public :: MUON_MAG_MOM_TO_BOHR_MAGNETON_RATIO = &
codata_constant("muon mag. mom. to Bohr magneton ratio", &
-4.84197047e-3_dp, 0.00000011e-3_dp, &
"") !! muon mag. mom. to Bohr magneton ratio

type(codata_constant), parameter, public :: MUON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO = &
codata_constant("muon mag. mom. to nuclear magneton ratio", &
-8.89059703_dp, 0.00000020_dp, &
"") !! muon mag. mom. to nuclear magneton ratio

type(codata_constant), parameter, public :: MUON_MASS = &
codata_constant("muon mass", &
1.883531627e-28_dp, 0.000000042e-28_dp, &
"kg") !! muon mass

type(codata_constant), parameter, public :: MUON_MASS_ENERGY_EQUIVALENT = &
codata_constant("muon mass energy equivalent", &
1.692833804e-11_dp, 0.000000038e-11_dp, &
"J") !! muon mass energy equivalent

type(codata_constant), parameter, public :: MUON_MASS_ENERGY_EQUIVALENT_IN_MEV = &
codata_constant("muon mass energy equivalent in MeV", &
105.6583755_dp, 0.0000023_dp, &
"MeV") !! muon mass energy equivalent in MeV

type(codata_constant), parameter, public :: MUON_MASS_IN_U = &
codata_constant("muon mass in u", &
0.1134289259_dp, 0.0000000025_dp, &
"u") !! muon mass in u

type(codata_constant), parameter, public :: MUON_MOLAR_MASS = &
codata_constant("muon molar mass", &
1.134289259e-4_dp, 0.000000025e-4_dp, &
"kg mol^-1") !! muon molar mass

type(codata_constant), parameter, public :: MUON_NEUTRON_MASS_RATIO = &
codata_constant("muon-neutron mass ratio", &
0.1124545170_dp, 0.0000000025_dp, &
"") !! muon-neutron mass ratio

type(codata_constant), parameter, public :: MUON_PROTON_MAG_MOM_RATIO = &
codata_constant("muon-proton mag. mom. ratio", &
-3.183345142_dp, 0.000000071_dp, &
"") !! muon-proton mag. mom. ratio

type(codata_constant), parameter, public :: MUON_PROTON_MASS_RATIO = &
codata_constant("muon-proton mass ratio", &
0.1126095264_dp, 0.0000000025_dp, &
"") !! muon-proton mass ratio

type(codata_constant), parameter, public :: MUON_TAU_MASS_RATIO = &
codata_constant("muon-tau mass ratio", &
5.94635e-2_dp, 0.00040e-2_dp, &
"") !! muon-tau mass ratio

type(codata_constant), parameter, public :: NATURAL_UNIT_OF_ACTION = &
codata_constant("natural unit of action", &
1.054571817e-34_dp, 0.0_dp, &
"J s") !! natural unit of action

type(codata_constant), parameter, public :: NATURAL_UNIT_OF_ACTION_IN_EV_S = &
codata_constant("natural unit of action in eV s", &
6.582119569e-16_dp, 0.0_dp, &
"eV s") !! natural unit of action in eV s

type(codata_constant), parameter, public :: NATURAL_UNIT_OF_ENERGY = &
codata_constant("natural unit of energy", &
8.1871057769e-14_dp, 0.0000000025e-14_dp, &
"J") !! natural unit of energy

type(codata_constant), parameter, public :: NATURAL_UNIT_OF_ENERGY_IN_MEV = &
codata_constant("natural unit of energy in MeV", &
0.51099895000_dp, 0.00000000015_dp, &
"MeV") !! natural unit of energy in MeV

type(codata_constant), parameter, public :: NATURAL_UNIT_OF_LENGTH = &
codata_constant("natural unit of length", &
3.8615926796e-13_dp, 0.0000000012e-13_dp, &
"m") !! natural unit of length

type(codata_constant), parameter, public :: NATURAL_UNIT_OF_MASS = &
codata_constant("natural unit of mass", &
9.1093837015e-31_dp, 0.0000000028e-31_dp, &
"kg") !! natural unit of mass

type(codata_constant), parameter, public :: NATURAL_UNIT_OF_MOMENTUM = &
codata_constant("natural unit of momentum", &
2.73092453075e-22_dp, 0.00000000082e-22_dp, &
"kg m s^-1") !! natural unit of momentum

type(codata_constant), parameter, public :: NATURAL_UNIT_OF_MOMENTUM_IN_MEV_C = &
codata_constant("natural unit of momentum in MeV/c", &
0.51099895000_dp, 0.00000000015_dp, &
"MeV/c") !! natural unit of momentum in MeV/c

type(codata_constant), parameter, public :: NATURAL_UNIT_OF_TIME = &
codata_constant("natural unit of time", &
1.28808866819e-21_dp, 0.00000000039e-21_dp, &
"s") !! natural unit of time

type(codata_constant), parameter, public :: NATURAL_UNIT_OF_VELOCITY = &
codata_constant("natural unit of velocity", &
299792458_dp, 0.0_dp, &
"m s^-1") !! natural unit of velocity

type(codata_constant), parameter, public :: NEUTRON_COMPTON_WAVELENGTH = &
codata_constant("neutron Compton wavelength", &
1.31959090581e-15_dp, 0.00000000075e-15_dp, &
"m") !! neutron Compton wavelength

type(codata_constant), parameter, public :: NEUTRON_ELECTRON_MAG_MOM_RATIO = &
codata_constant("neutron-electron mag. mom. ratio", &
1.04066882e-3_dp, 0.00000025e-3_dp, &
"") !! neutron-electron mag. mom. ratio

type(codata_constant), parameter, public :: NEUTRON_ELECTRON_MASS_RATIO = &
codata_constant("neutron-electron mass ratio", &
1838.68366173_dp, 0.00000089_dp, &
"") !! neutron-electron mass ratio

type(codata_constant), parameter, public :: NEUTRON_G_FACTOR = &
codata_constant("neutron g factor", &
-3.82608545_dp, 0.00000090_dp, &
"") !! neutron g factor

type(codata_constant), parameter, public :: NEUTRON_GYROMAG_RATIO = &
codata_constant("neutron gyromag. ratio", &
1.83247171e8_dp, 0.00000043e8_dp, &
"s^-1 T^-1") !! neutron gyromag. ratio

type(codata_constant), parameter, public :: NEUTRON_GYROMAG_RATIO_IN_MHZ_T = &
codata_constant("neutron gyromag. ratio in MHz/T", &
29.1646931_dp, 0.0000069_dp, &
"MHz T^-1") !! neutron gyromag. ratio in MHz/T

type(codata_constant), parameter, public :: NEUTRON_MAG_MOM = &
codata_constant("neutron mag. mom.", &
-9.6623651e-27_dp, 0.0000023e-27_dp, &
"J T^-1") !! neutron mag. mom.

type(codata_constant), parameter, public :: NEUTRON_MAG_MOM_TO_BOHR_MAGNETON_RATIO = &
codata_constant("neutron mag. mom. to Bohr magneton ratio", &
-1.04187563e-3_dp, 0.00000025e-3_dp, &
"") !! neutron mag. mom. to Bohr magneton ratio

type(codata_constant), parameter, public :: NEUTRON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO = &
codata_constant("neutron mag. mom. to nuclear magneton ratio", &
-1.91304273_dp, 0.00000045_dp, &
"") !! neutron mag. mom. to nuclear magneton ratio

type(codata_constant), parameter, public :: NEUTRON_MASS = &
codata_constant("neutron mass", &
1.67492749804e-27_dp, 0.00000000095e-27_dp, &
"kg") !! neutron mass

type(codata_constant), parameter, public :: NEUTRON_MASS_ENERGY_EQUIVALENT = &
codata_constant("neutron mass energy equivalent", &
1.50534976287e-10_dp, 0.00000000086e-10_dp, &
"J") !! neutron mass energy equivalent

type(codata_constant), parameter, public :: NEUTRON_MASS_ENERGY_EQUIVALENT_IN_MEV = &
codata_constant("neutron mass energy equivalent in MeV", &
939.56542052_dp, 0.00000054_dp, &
"MeV") !! neutron mass energy equivalent in MeV

type(codata_constant), parameter, public :: NEUTRON_MASS_IN_U = &
codata_constant("neutron mass in u", &
1.00866491595_dp, 0.00000000049_dp, &
"u") !! neutron mass in u

type(codata_constant), parameter, public :: NEUTRON_MOLAR_MASS = &
codata_constant("neutron molar mass", &
1.00866491560e-3_dp, 0.00000000057e-3_dp, &
"kg mol^-1") !! neutron molar mass

type(codata_constant), parameter, public :: NEUTRON_MUON_MASS_RATIO = &
codata_constant("neutron-muon mass ratio", &
8.89248406_dp, 0.00000020_dp, &
"") !! neutron-muon mass ratio

type(codata_constant), parameter, public :: NEUTRON_PROTON_MAG_MOM_RATIO = &
codata_constant("neutron-proton mag. mom. ratio", &
-0.68497934_dp, 0.00000016_dp, &
"") !! neutron-proton mag. mom. ratio

type(codata_constant), parameter, public :: NEUTRON_PROTON_MASS_DIFFERENCE = &
codata_constant("neutron-proton mass difference", &
2.30557435e-30_dp, 0.00000082e-30_dp, &
"kg") !! neutron-proton mass difference

type(codata_constant), parameter, public :: NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT = &
codata_constant("neutron-proton mass difference energy equivalent", &
2.07214689e-13_dp, 0.00000074e-13_dp, &
"J") !! neutron-proton mass difference energy equivalent

type(codata_constant), parameter, public :: NEUTRON_PROTON_MASS_DIFFERENCE_ENERGY_EQUIVALENT_IN_MEV = &
codata_constant("neutron-proton mass difference energy equivalent in MeV", &
1.29333236_dp, 0.00000046_dp, &
"MeV") !! neutron-proton mass difference energy equivalent in MeV

type(codata_constant), parameter, public :: NEUTRON_PROTON_MASS_DIFFERENCE_IN_U = &
codata_constant("neutron-proton mass difference in u", &
1.38844933e-3_dp, 0.00000049e-3_dp, &
"u") !! neutron-proton mass difference in u

type(codata_constant), parameter, public :: NEUTRON_PROTON_MASS_RATIO = &
codata_constant("neutron-proton mass ratio", &
1.00137841931_dp, 0.00000000049_dp, &
"") !! neutron-proton mass ratio

type(codata_constant), parameter, public :: NEUTRON_RELATIVE_ATOMIC_MASS = &
codata_constant("neutron relative atomic mass", &
1.00866491595_dp, 0.00000000049_dp, &
"") !! neutron relative atomic mass

type(codata_constant), parameter, public :: NEUTRON_TAU_MASS_RATIO = &
codata_constant("neutron-tau mass ratio", &
0.528779_dp, 0.000036_dp, &
"") !! neutron-tau mass ratio

type(codata_constant), parameter, public :: NEUTRON_TO_SHIELDED_PROTON_MAG_MOM_RATIO = &
codata_constant("neutron to shielded proton mag. mom. ratio", &
-0.68499694_dp, 0.00000016_dp, &
"") !! neutron to shielded proton mag. mom. ratio

type(codata_constant), parameter, public :: NEWTONIAN_CONSTANT_OF_GRAVITATION = &
codata_constant("Newtonian constant of gravitation", &
6.67430e-11_dp, 0.00015e-11_dp, &
"m^3 kg^-1 s^-2") !! Newtonian constant of gravitation

type(codata_constant), parameter, public :: NEWTONIAN_CONSTANT_OF_GRAVITATION_OVER_H_BAR_C = &
codata_constant("Newtonian constant of gravitation over h-bar c", &
6.70883e-39_dp, 0.00015e-39_dp, &
"(GeV/c^2)^-2") !! Newtonian constant of gravitation over h-bar c

type(codata_constant), parameter, public :: NUCLEAR_MAGNETON = &
codata_constant("nuclear magneton", &
5.0507837461e-27_dp, 0.0000000015e-27_dp, &
"J T^-1") !! nuclear magneton

type(codata_constant), parameter, public :: NUCLEAR_MAGNETON_IN_EV_T = &
codata_constant("nuclear magneton in eV/T", &
3.15245125844e-8_dp, 0.00000000096e-8_dp, &
"eV T^-1") !! nuclear magneton in eV/T

type(codata_constant), parameter, public :: NUCLEAR_MAGNETON_IN_INVERSE_METER_PER_TESLA = &
codata_constant("nuclear magneton in inverse meter per tesla", &
2.54262341353e-2_dp, 0.00000000078e-2_dp, &
"m^-1 T^-1") !! nuclear magneton in inverse meter per tesla

type(codata_constant), parameter, public :: NUCLEAR_MAGNETON_IN_K_T = &
codata_constant("nuclear magneton in K/T", &
3.6582677756e-4_dp, 0.0000000011e-4_dp, &
"K T^-1") !! nuclear magneton in K/T

type(codata_constant), parameter, public :: NUCLEAR_MAGNETON_IN_MHZ_T = &
codata_constant("nuclear magneton in MHz/T", &
7.6225932291_dp, 0.0000000023_dp, &
"MHz T^-1") !! nuclear magneton in MHz/T

type(codata_constant), parameter, public :: PLANCK_CONSTANT = &
codata_constant("Planck constant", &
6.62607015e-34_dp, 0.0_dp, &
"J Hz^-1") !! Planck constant

type(codata_constant), parameter, public :: PLANCK_CONSTANT_IN_EV_HZ = &
codata_constant("Planck constant in eV/Hz", &
4.135667696e-15_dp, 0.0_dp, &
"eV Hz^-1") !! Planck constant in eV/Hz

type(codata_constant), parameter, public :: PLANCK_LENGTH = &
codata_constant("Planck length", &
1.616255e-35_dp, 0.000018e-35_dp, &
"m") !! Planck length

type(codata_constant), parameter, public :: PLANCK_MASS = &
codata_constant("Planck mass", &
2.176434e-8_dp, 0.000024e-8_dp, &
"kg") !! Planck mass

type(codata_constant), parameter, public :: PLANCK_MASS_ENERGY_EQUIVALENT_IN_GEV = &
codata_constant("Planck mass energy equivalent in GeV", &
1.220890e19_dp, 0.000014e19_dp, &
"GeV") !! Planck mass energy equivalent in GeV

type(codata_constant), parameter, public :: PLANCK_TEMPERATURE = &
codata_constant("Planck temperature", &
1.416784e32_dp, 0.000016e32_dp, &
"K") !! Planck temperature

type(codata_constant), parameter, public :: PLANCK_TIME = &
codata_constant("Planck time", &
5.391247e-44_dp, 0.000060e-44_dp, &
"s") !! Planck time

type(codata_constant), parameter, public :: PROTON_CHARGE_TO_MASS_QUOTIENT = &
codata_constant("proton charge to mass quotient", &
9.5788331560e7_dp, 0.0000000029e7_dp, &
"C kg^-1") !! proton charge to mass quotient

type(codata_constant), parameter, public :: PROTON_COMPTON_WAVELENGTH = &
codata_constant("proton Compton wavelength", &
1.32140985539e-15_dp, 0.00000000040e-15_dp, &
"m") !! proton Compton wavelength

type(codata_constant), parameter, public :: PROTON_ELECTRON_MASS_RATIO = &
codata_constant("proton-electron mass ratio", &
1836.15267343_dp, 0.00000011_dp, &
"") !! proton-electron mass ratio

type(codata_constant), parameter, public :: PROTON_G_FACTOR = &
codata_constant("proton g factor", &
5.5856946893_dp, 0.0000000016_dp, &
"") !! proton g factor

type(codata_constant), parameter, public :: PROTON_GYROMAG_RATIO = &
codata_constant("proton gyromag. ratio", &
2.6752218744e8_dp, 0.0000000011e8_dp, &
"s^-1 T^-1") !! proton gyromag. ratio

type(codata_constant), parameter, public :: PROTON_GYROMAG_RATIO_IN_MHZ_T = &
codata_constant("proton gyromag. ratio in MHz/T", &
42.577478518_dp, 0.000000018_dp, &
"MHz T^-1") !! proton gyromag. ratio in MHz/T

type(codata_constant), parameter, public :: PROTON_MAG_MOM = &
codata_constant("proton mag. mom.", &
1.41060679736e-26_dp, 0.00000000060e-26_dp, &
"J T^-1") !! proton mag. mom.

type(codata_constant), parameter, public :: PROTON_MAG_MOM_TO_BOHR_MAGNETON_RATIO = &
codata_constant("proton mag. mom. to Bohr magneton ratio", &
1.52103220230e-3_dp, 0.00000000046e-3_dp, &
"") !! proton mag. mom. to Bohr magneton ratio

type(codata_constant), parameter, public :: PROTON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO = &
codata_constant("proton mag. mom. to nuclear magneton ratio", &
2.79284734463_dp, 0.00000000082_dp, &
"") !! proton mag. mom. to nuclear magneton ratio

type(codata_constant), parameter, public :: PROTON_MAG_SHIELDING_CORRECTION = &
codata_constant("proton mag. shielding correction", &
2.5689e-5_dp, 0.0011e-5_dp, &
"") !! proton mag. shielding correction

type(codata_constant), parameter, public :: PROTON_MASS = &
codata_constant("proton mass", &
1.67262192369e-27_dp, 0.00000000051e-27_dp, &
"kg") !! proton mass

type(codata_constant), parameter, public :: PROTON_MASS_ENERGY_EQUIVALENT = &
codata_constant("proton mass energy equivalent", &
1.50327761598e-10_dp, 0.00000000046e-10_dp, &
"J") !! proton mass energy equivalent

type(codata_constant), parameter, public :: PROTON_MASS_ENERGY_EQUIVALENT_IN_MEV = &
codata_constant("proton mass energy equivalent in MeV", &
938.27208816_dp, 0.00000029_dp, &
"MeV") !! proton mass energy equivalent in MeV

type(codata_constant), parameter, public :: PROTON_MASS_IN_U = &
codata_constant("proton mass in u", &
1.007276466621_dp, 0.000000000053_dp, &
"u") !! proton mass in u

type(codata_constant), parameter, public :: PROTON_MOLAR_MASS = &
codata_constant("proton molar mass", &
1.00727646627e-3_dp, 0.00000000031e-3_dp, &
"kg mol^-1") !! proton molar mass

type(codata_constant), parameter, public :: PROTON_MUON_MASS_RATIO = &
codata_constant("proton-muon mass ratio", &
8.88024337_dp, 0.00000020_dp, &
"") !! proton-muon mass ratio

type(codata_constant), parameter, public :: PROTON_NEUTRON_MAG_MOM_RATIO = &
codata_constant("proton-neutron mag. mom. ratio", &
-1.45989805_dp, 0.00000034_dp, &
"") !! proton-neutron mag. mom. ratio

type(codata_constant), parameter, public :: PROTON_NEUTRON_MASS_RATIO = &
codata_constant("proton-neutron mass ratio", &
0.99862347812_dp, 0.00000000049_dp, &
"") !! proton-neutron mass ratio

type(codata_constant), parameter, public :: PROTON_RELATIVE_ATOMIC_MASS = &
codata_constant("proton relative atomic mass", &
1.007276466621_dp, 0.000000000053_dp, &
"") !! proton relative atomic mass

type(codata_constant), parameter, public :: PROTON_RMS_CHARGE_RADIUS = &
codata_constant("proton rms charge radius", &
8.414e-16_dp, 0.019e-16_dp, &
"m") !! proton rms charge radius

type(codata_constant), parameter, public :: PROTON_TAU_MASS_RATIO = &
codata_constant("proton-tau mass ratio", &
0.528051_dp, 0.000036_dp, &
"") !! proton-tau mass ratio

type(codata_constant), parameter, public :: QUANTUM_OF_CIRCULATION = &
codata_constant("quantum of circulation", &
3.6369475516e-4_dp, 0.0000000011e-4_dp, &
"m^2 s^-1") !! quantum of circulation

type(codata_constant), parameter, public :: QUANTUM_OF_CIRCULATION_TIMES_2 = &
codata_constant("quantum of circulation times 2", &
7.2738951032e-4_dp, 0.0000000022e-4_dp, &
"m^2 s^-1") !! quantum of circulation times 2

type(codata_constant), parameter, public :: REDUCED_COMPTON_WAVELENGTH = &
codata_constant("reduced Compton wavelength", &
3.8615926796e-13_dp, 0.0000000012e-13_dp, &
"m") !! reduced Compton wavelength

type(codata_constant), parameter, public :: REDUCED_MUON_COMPTON_WAVELENGTH = &
codata_constant("reduced muon Compton wavelength", &
1.867594306e-15_dp, 0.000000042e-15_dp, &
"m") !! reduced muon Compton wavelength

type(codata_constant), parameter, public :: REDUCED_NEUTRON_COMPTON_WAVELENGTH = &
codata_constant("reduced neutron Compton wavelength", &
2.1001941552e-16_dp, 0.0000000012e-16_dp, &
"m") !! reduced neutron Compton wavelength

type(codata_constant), parameter, public :: REDUCED_PLANCK_CONSTANT = &
codata_constant("reduced Planck constant", &
1.054571817e-34_dp, 0.0_dp, &
"J s") !! reduced Planck constant

type(codata_constant), parameter, public :: REDUCED_PLANCK_CONSTANT_IN_EV_S = &
codata_constant("reduced Planck constant in eV s", &
6.582119569e-16_dp, 0.0_dp, &
"eV s") !! reduced Planck constant in eV s

type(codata_constant), parameter, public :: REDUCED_PLANCK_CONSTANT_TIMES_C_IN_MEV_FM = &
codata_constant("reduced Planck constant times c in MeV fm", &
197.3269804_dp, 0.0_dp, &
"MeV fm") !! reduced Planck constant times c in MeV fm

type(codata_constant), parameter, public :: REDUCED_PROTON_COMPTON_WAVELENGTH = &
codata_constant("reduced proton Compton wavelength", &
2.10308910336e-16_dp, 0.00000000064e-16_dp, &
"m") !! reduced proton Compton wavelength

type(codata_constant), parameter, public :: REDUCED_TAU_COMPTON_WAVELENGTH = &
codata_constant("reduced tau Compton wavelength", &
1.110538e-16_dp, 0.000075e-16_dp, &
"m") !! reduced tau Compton wavelength

type(codata_constant), parameter, public :: RYDBERG_CONSTANT = &
codata_constant("Rydberg constant", &
10973731.568160_dp, 0.000021_dp, &
"m^-1") !! Rydberg constant

type(codata_constant), parameter, public :: RYDBERG_CONSTANT_TIMES_C_IN_HZ = &
codata_constant("Rydberg constant times c in Hz", &
3.2898419602508e15_dp, 0.0000000000064e15_dp, &
"Hz") !! Rydberg constant times c in Hz

type(codata_constant), parameter, public :: RYDBERG_CONSTANT_TIMES_HC_IN_EV = &
codata_constant("Rydberg constant times hc in eV", &
13.605693122994_dp, 0.000000000026_dp, &
"eV") !! Rydberg constant times hc in eV

type(codata_constant), parameter, public :: RYDBERG_CONSTANT_TIMES_HC_IN_J = &
codata_constant("Rydberg constant times hc in J", &
2.1798723611035e-18_dp, 0.0000000000042e-18_dp, &
"J") !! Rydberg constant times hc in J

type(codata_constant), parameter, public :: SACKUR_TETRODE_CONSTANT_1_K_100_KPA = &
codata_constant("Sackur-Tetrode constant (1 K, 100 kPa)", &
-1.15170753706_dp, 0.00000000045_dp, &
"") !! Sackur-Tetrode constant (1 K, 100 kPa)

type(codata_constant), parameter, public :: SACKUR_TETRODE_CONSTANT_1_K_101325_KPA = &
codata_constant("Sackur-Tetrode constant (1 K, 101.325 kPa)", &
-1.16487052358_dp, 0.00000000045_dp, &
"") !! Sackur-Tetrode constant (1 K, 101.325 kPa)

type(codata_constant), parameter, public :: SECOND_RADIATION_CONSTANT = &
codata_constant("second radiation constant", &
1.438776877e-2_dp, 0.0_dp, &
"m K") !! second radiation constant

type(codata_constant), parameter, public :: SHIELDED_HELION_GYROMAG_RATIO = &
codata_constant("shielded helion gyromag. ratio", &
2.037894569e8_dp, 0.000000024e8_dp, &
"s^-1 T^-1") !! shielded helion gyromag. ratio

type(codata_constant), parameter, public :: SHIELDED_HELION_GYROMAG_RATIO_IN_MHZ_T = &
codata_constant("shielded helion gyromag. ratio in MHz/T", &
32.43409942_dp, 0.00000038_dp, &
"MHz T^-1") !! shielded helion gyromag. ratio in MHz/T

type(codata_constant), parameter, public :: SHIELDED_HELION_MAG_MOM = &
codata_constant("shielded helion mag. mom.", &
-1.074553090e-26_dp, 0.000000013e-26_dp, &
"J T^-1") !! shielded helion mag. mom.

type(codata_constant), parameter, public :: SHIELDED_HELION_MAG_MOM_TO_BOHR_MAGNETON_RATIO = &
codata_constant("shielded helion mag. mom. to Bohr magneton ratio", &
-1.158671471e-3_dp, 0.000000014e-3_dp, &
"") !! shielded helion mag. mom. to Bohr magneton ratio

type(codata_constant), parameter, public :: SHIELDED_HELION_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO = &
codata_constant("shielded helion mag. mom. to nuclear magneton ratio", &
-2.127497719_dp, 0.000000025_dp, &
"") !! shielded helion mag. mom. to nuclear magneton ratio

type(codata_constant), parameter, public :: SHIELDED_HELION_TO_PROTON_MAG_MOM_RATIO = &
codata_constant("shielded helion to proton mag. mom. ratio", &
-0.7617665618_dp, 0.0000000089_dp, &
"") !! shielded helion to proton mag. mom. ratio

type(codata_constant), parameter, public :: SHIELDED_HELION_TO_SHIELDED_PROTON_MAG_MOM_RATIO = &
codata_constant("shielded helion to shielded proton mag. mom. ratio", &
-0.7617861313_dp, 0.0000000033_dp, &
"") !! shielded helion to shielded proton mag. mom. ratio

type(codata_constant), parameter, public :: SHIELDED_PROTON_GYROMAG_RATIO = &
codata_constant("shielded proton gyromag. ratio", &
2.675153151e8_dp, 0.000000029e8_dp, &
"s^-1 T^-1") !! shielded proton gyromag. ratio

type(codata_constant), parameter, public :: SHIELDED_PROTON_GYROMAG_RATIO_IN_MHZ_T = &
codata_constant("shielded proton gyromag. ratio in MHz/T", &
42.57638474_dp, 0.00000046_dp, &
"MHz T^-1") !! shielded proton gyromag. ratio in MHz/T

type(codata_constant), parameter, public :: SHIELDED_PROTON_MAG_MOM = &
codata_constant("shielded proton mag. mom.", &
1.410570560e-26_dp, 0.000000015e-26_dp, &
"J T^-1") !! shielded proton mag. mom.

type(codata_constant), parameter, public :: SHIELDED_PROTON_MAG_MOM_TO_BOHR_MAGNETON_RATIO = &
codata_constant("shielded proton mag. mom. to Bohr magneton ratio", &
1.520993128e-3_dp, 0.000000017e-3_dp, &
"") !! shielded proton mag. mom. to Bohr magneton ratio

type(codata_constant), parameter, public :: SHIELDED_PROTON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO = &
codata_constant("shielded proton mag. mom. to nuclear magneton ratio", &
2.792775599_dp, 0.000000030_dp, &
"") !! shielded proton mag. mom. to nuclear magneton ratio

type(codata_constant), parameter, public :: SHIELDING_DIFFERENCE_OF_D_AND_P_IN_HD = &
codata_constant("shielding difference of d and p in HD", &
2.0200e-8_dp, 0.0020e-8_dp, &
"") !! shielding difference of d and p in HD

type(codata_constant), parameter, public :: SHIELDING_DIFFERENCE_OF_T_AND_P_IN_HT = &
codata_constant("shielding difference of t and p in HT", &
2.4140e-8_dp, 0.0020e-8_dp, &
"") !! shielding difference of t and p in HT

type(codata_constant), parameter, public :: SPEED_OF_LIGHT_IN_VACUUM = &
codata_constant("speed of light in vacuum", &
299792458_dp, 0.0_dp, &
"m s^-1") !! speed of light in vacuum

type(codata_constant), parameter, public :: STANDARD_ACCELERATION_OF_GRAVITY = &
codata_constant("standard acceleration of gravity", &
9.80665_dp, 0.0_dp, &
"m s^-2") !! standard acceleration of gravity

type(codata_constant), parameter, public :: STANDARD_ATMOSPHERE = &
codata_constant("standard atmosphere", &
101325_dp, 0.0_dp, &
"Pa") !! standard atmosphere

type(codata_constant), parameter, public :: STANDARD_STATE_PRESSURE = &
codata_constant("standard-state pressure", &
100000_dp, 0.0_dp, &
"Pa") !! standard-state pressure

type(codata_constant), parameter, public :: STEFAN_BOLTZMANN_CONSTANT = &
codata_constant("Stefan-Boltzmann constant", &
5.670374419e-8_dp, 0.0_dp, &
"W m^-2 K^-4") !! Stefan-Boltzmann constant

type(codata_constant), parameter, public :: TAU_COMPTON_WAVELENGTH = &
codata_constant("tau Compton wavelength", &
6.97771e-16_dp, 0.00047e-16_dp, &
"m") !! tau Compton wavelength

type(codata_constant), parameter, public :: TAU_ELECTRON_MASS_RATIO = &
codata_constant("tau-electron mass ratio", &
3477.23_dp, 0.23_dp, &
"") !! tau-electron mass ratio

type(codata_constant), parameter, public :: TAU_ENERGY_EQUIVALENT = &
codata_constant("tau energy equivalent", &
1776.86_dp, 0.12_dp, &
"MeV") !! tau energy equivalent

type(codata_constant), parameter, public :: TAU_MASS = &
codata_constant("tau mass", &
3.16754e-27_dp, 0.00021e-27_dp, &
"kg") !! tau mass

type(codata_constant), parameter, public :: TAU_MASS_ENERGY_EQUIVALENT = &
codata_constant("tau mass energy equivalent", &
2.84684e-10_dp, 0.00019e-10_dp, &
"J") !! tau mass energy equivalent

type(codata_constant), parameter, public :: TAU_MASS_IN_U = &
codata_constant("tau mass in u", &
1.90754_dp, 0.00013_dp, &
"u") !! tau mass in u

type(codata_constant), parameter, public :: TAU_MOLAR_MASS = &
codata_constant("tau molar mass", &
1.90754e-3_dp, 0.00013e-3_dp, &
"kg mol^-1") !! tau molar mass

type(codata_constant), parameter, public :: TAU_MUON_MASS_RATIO = &
codata_constant("tau-muon mass ratio", &
16.8170_dp, 0.0011_dp, &
"") !! tau-muon mass ratio

type(codata_constant), parameter, public :: TAU_NEUTRON_MASS_RATIO = &
codata_constant("tau-neutron mass ratio", &
1.89115_dp, 0.00013_dp, &
"") !! tau-neutron mass ratio

type(codata_constant), parameter, public :: TAU_PROTON_MASS_RATIO = &
codata_constant("tau-proton mass ratio", &
1.89376_dp, 0.00013_dp, &
"") !! tau-proton mass ratio

type(codata_constant), parameter, public :: THOMSON_CROSS_SECTION = &
codata_constant("Thomson cross section", &
6.6524587321e-29_dp, 0.0000000060e-29_dp, &
"m^2") !! Thomson cross section

type(codata_constant), parameter, public :: TRITON_ELECTRON_MASS_RATIO = &
codata_constant("triton-electron mass ratio", &
5496.92153573_dp, 0.00000027_dp, &
"") !! triton-electron mass ratio

type(codata_constant), parameter, public :: TRITON_G_FACTOR = &
codata_constant("triton g factor", &
5.957924931_dp, 0.000000012_dp, &
"") !! triton g factor

type(codata_constant), parameter, public :: TRITON_MAG_MOM = &
codata_constant("triton mag. mom.", &
1.5046095202e-26_dp, 0.0000000030e-26_dp, &
"J T^-1") !! triton mag. mom.

type(codata_constant), parameter, public :: TRITON_MAG_MOM_TO_BOHR_MAGNETON_RATIO = &
codata_constant("triton mag. mom. to Bohr magneton ratio", &
1.6223936651e-3_dp, 0.0000000032e-3_dp, &
"") !! triton mag. mom. to Bohr magneton ratio

type(codata_constant), parameter, public :: TRITON_MAG_MOM_TO_NUCLEAR_MAGNETON_RATIO = &
codata_constant("triton mag. mom. to nuclear magneton ratio", &
2.9789624656_dp, 0.0000000059_dp, &
"") !! triton mag. mom. to nuclear magneton ratio

type(codata_constant), parameter, public :: TRITON_MASS = &
codata_constant("triton mass", &
5.0073567446e-27_dp, 0.0000000015e-27_dp, &
"kg") !! triton mass

type(codata_constant), parameter, public :: TRITON_MASS_ENERGY_EQUIVALENT = &
codata_constant("triton mass energy equivalent", &
4.5003878060e-10_dp, 0.0000000014e-10_dp, &
"J") !! triton mass energy equivalent

type(codata_constant), parameter, public :: TRITON_MASS_ENERGY_EQUIVALENT_IN_MEV = &
codata_constant("triton mass energy equivalent in MeV", &
2808.92113298_dp, 0.00000085_dp, &
"MeV") !! triton mass energy equivalent in MeV

type(codata_constant), parameter, public :: TRITON_MASS_IN_U = &
codata_constant("triton mass in u", &
3.01550071621_dp, 0.00000000012_dp, &
"u") !! triton mass in u

type(codata_constant), parameter, public :: TRITON_MOLAR_MASS = &
codata_constant("triton molar mass", &
3.01550071517e-3_dp, 0.00000000092e-3_dp, &
"kg mol^-1") !! triton molar mass

type(codata_constant), parameter, public :: TRITON_PROTON_MASS_RATIO = &
codata_constant("triton-proton mass ratio", &
2.99371703414_dp, 0.00000000015_dp, &
"") !! triton-proton mass ratio

type(codata_constant), parameter, public :: TRITON_RELATIVE_ATOMIC_MASS = &
codata_constant("triton relative atomic mass", &
3.01550071621_dp, 0.00000000012_dp, &
"") !! triton relative atomic mass

type(codata_constant), parameter, public :: TRITON_TO_PROTON_MAG_MOM_RATIO = &
codata_constant("triton to proton mag. mom. ratio", &
1.0666399191_dp, 0.0000000021_dp, &
"") !! triton to proton mag. mom. ratio

type(codata_constant), parameter, public :: UNIFIED_ATOMIC_MASS_UNIT = &
codata_constant("unified atomic mass unit", &
1.66053906660e-27_dp, 0.00000000050e-27_dp, &
"kg") !! unified atomic mass unit

type(codata_constant), parameter, public :: VACUUM_ELECTRIC_PERMITTIVITY = &
codata_constant("vacuum electric permittivity", &
8.8541878128e-12_dp, 0.0000000013e-12_dp, &
"F m^-1") !! vacuum electric permittivity

type(codata_constant), parameter, public :: VACUUM_MAG_PERMEABILITY = &
codata_constant("vacuum mag. permeability", &
1.25663706212e-6_dp, 0.00000000019e-6_dp, &
"N A^-2") !! vacuum mag. permeability

type(codata_constant), parameter, public :: VON_KLITZING_CONSTANT = &
codata_constant("von Klitzing constant", &
25812.80745_dp, 0.0_dp, &
"ohm") !! von Klitzing constant

type(codata_constant), parameter, public :: WEAK_MIXING_ANGLE = &
codata_constant("weak mixing angle", &
0.22290_dp, 0.00030_dp, &
"") !! weak mixing angle

type(codata_constant), parameter, public :: WIEN_FREQUENCY_DISPLACEMENT_LAW_CONSTANT = &
codata_constant("Wien frequency displacement law constant", &
5.878925757e10_dp, 0.0_dp, &
"Hz K^-1") !! Wien frequency displacement law constant

type(codata_constant), parameter, public :: WIEN_WAVELENGTH_DISPLACEMENT_LAW_CONSTANT = &
codata_constant("Wien wavelength displacement law constant", &
2.897771955e-3_dp, 0.0_dp, &
"m K") !! Wien wavelength displacement law constant

type(codata_constant), parameter, public :: W_TO_Z_MASS_RATIO = &
codata_constant("W to Z mass ratio", &
0.88153_dp, 0.00017_dp, &
"") !! W to Z mass ratio

end module stdlib_codata