name: CI_Flang

on: [push, pull_request]

env:
  CMAKE_BUILD_PARALLEL_LEVEL: "2"
  CTEST_OUTPUT_ON_FAILURE: "ON"
  CTEST_PARALLEL_LEVEL: "2"
  CTEST_TIME_TIMEOUT: "5"

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install fypp and ninja
      run: pip install --upgrade fypp ninja

    - name: Install Flang and Clang
      run: |
        sudo apt-get update -y
        sudo apt-get install -y flang clang

    - name: Configure with CMake
      run: >-
        cmake -Wdev -G Ninja
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_Fortran_COMPILER=flang
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_MAXIMUM_RANK:String=4
        -DCMAKE_INSTALL_PREFIX=$PWD/_dist
        -DFIND_BLAS:STRING=FALSE
        -DWITH_XDP=off
        -DWITH_QP=off
        -S . -B build

    - name: Build and compile
      run: cmake --build build --parallel

    - name: Catch build fail
      if: failure()
      run: cmake --build build --verbose --parallel 1

    - name: Test
      run: >-
        ctest
        --test-dir build
        --parallel
        --output-on-failure
        --no-tests=error

    - name: Install project
      run: cmake --install build
