name: CI_Flang

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CMAKE_BUILD_PARALLEL_LEVEL: "2"
  CTEST_PARALLEL_LEVEL: "2"
  CTEST_TEST_TIMEOUT: "5"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install fypp
      run: pip install --upgrade fypp

    - name: Setup Flang
      uses: minhqdao/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: flang
        version: latest

    - name: Configure with CMake
      run: >-
        cmake -Wdev
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_Fortran_COMPILER=${{ steps.setup-fortran.outputs.fc }}
        -DCMAKE_C_COMPILER=${{ steps.setup-fortran.outputs.cc }}
        -DCMAKE_MAXIMUM_RANK:STRING=4
        -DCMAKE_INSTALL_PREFIX=$PWD/_dist
        -DFIND_BLAS:BOOL=FALSE
        -DWITH_XDP=off
        -DWITH_QP=off
        -S . -B build

    - name: Build
      run: cmake --build build --parallel

    - name: Catch build fail
      if: failure()
      run: cmake --build build --verbose --parallel 1

    - name: Test
      run: >-
        ctest
        --test-dir build
        --parallel
        --output-on-failure
        --no-tests=error

    - name: Install project
      run: cmake --install build
