name: ci_real128

on: [push, pull_request]

env:
  CI: "ON"

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.x

    - name: Set up CMake
      run: pip install --upgrade cmake

    - name: Cmake configure
    - run: cmake -DREAL128=true -B build
      env:
        FC: gfortran
        CC: gcc
        CXX: g++

    - name: CMake build
      run: cmake --build build --parallel

    - run: cmake --build build --verbose --parallel 1
      if: failure()

    - name: CTest
      run: ctest --output-on-failure --parallel -V
      working-directory: build

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Real128CMakeTestlog
        path: build/Testing/Temporary/LastTest.log