name: Draft PDF
on:
  push:
    paths:
      - joss/**
      - .github/workflows/draft-pdf.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: joss/paper_sparse.md

      - name: Move PDF into joss folder
        run: mv paper.pdf joss/paper_sparse.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper_sparse
          path: joss/paper_sparse.pdf